CREATE OR REPLACE TYPE ab_94676.FNMATRICIELLE                                          UNDER FONCTIONUNIVARIABLE
(
  Points FNMATRICIELLEPOINT,
 
  OVERRIDING MEMBER FUNCTION obtenirBorneInferieure RETURN DOUBLE PRECISION,
  OVERRIDING MEMBER FUNCTION obtenirBorneSuperieure RETURN DOUBLE PRECISION,
  OVERRIDING MEMBER FUNCTION evaluer(x DOUBLE PRECISION) RETURN DOUBLE PRECISION,
  OVERRIDING MEMBER FUNCTION inverser(y DOUBLE PRECISION) RETURN DOUBLE PRECISION
);
/