CREATE OR REPLACE TYPE ab_94676.FNQDOUVERTUREPARTIELLE                                          AS OBJECT
(
  ConstanteK DOUBLE PRECISION,
  ConstanteM DOUBLE PRECISION,
  ConstanteN DOUBLE PRECISION,
  ConstanteP DOUBLE PRECISION,
 
  ConstantesE FNQDCONSTANTESOUVPART,
  ConstantesH FNQDCONSTANTESOUVPART,
 
  CoefficientDebitZ1 FNUNIVARIABLEMORCEAUX,
  CoefficientDebitZ2 FNUNIVARIABLEMORCEAUX,
 
  MEMBER FUNCTION evaluer(y1 DOUBLE PRECISION, w DOUBLE PRECISION) RETURN DOUBLE PRECISION
);
/