CREATE OR REPLACE TYPE ab_94676.FNUNIVARIABLEMORCEAUX                                          AS OBJECT
(
  Nom VARCHAR(20),
  Segments FNUNIVARIABLESEGMENTS,
 
  MEMBER FUNCTION obtenirBorneInferieure RETURN DOUBLE PRECISION,
  MEMBER FUNCTION obtenirBorneSuperieure RETURN DOUBLE PRECISION,
  MEMBER FUNCTION evaluer(x DOUBLE PRECISION) RETURN DOUBLE PRECISION,
  MEMBER FUNCTION inverser(y DOUBLE PRECISION) RETURN DOUBLE PRECISION
);
/