CREATE OR REPLACE TYPE ab_94676.FONCTIONUNIVARIABLE                                          AS OBJECT
(
  Nom VARCHAR(20),
  NOT INSTANTIABLE MEMBER FUNCTION obtenirBorneInferieure RETURN DOUBLE PRECISION,
  NOT INSTANTIABLE MEMBER FUNCTION obtenirBorneSuperieure RETURN DOUBLE PRECISION,
  NOT INSTANTIABLE MEMBER FUNCTION evaluer(x DOUBLE PRECISION) RETURN DOUBLE PRECISION,
  NOT INSTANTIABLE MEMBER FUNCTION inverser(y DOUBLE PRECISION) RETURN DOUBLE PRECISION
) NOT FINAL NOT INSTANTIABLE;
/