CREATE TABLE sbxtax4.a_authority_requirements (
  authority_requirement_id NUMBER,
  "NAME" VARCHAR2(100 CHAR),
  start_date DATE,
  end_date DATE,
  "CONDITION" VARCHAR2(100 CHAR),
  "VALUE" VARCHAR2(100 CHAR),
  authority_id NUMBER,
  merchant_id NUMBER,
  created_by NUMBER,
  creation_date DATE,
  last_updated_by NUMBER,
  last_update_date DATE,
  synchronization_timestamp TIMESTAMP,
  authority_requirement_id_o NUMBER,
  name_o VARCHAR2(100 CHAR),
  start_date_o DATE,
  end_date_o DATE,
  condition_o VARCHAR2(100 CHAR),
  value_o VARCHAR2(100 CHAR),
  authority_id_o NUMBER,
  merchant_id_o NUMBER,
  created_by_o NUMBER,
  creation_date_o DATE,
  last_updated_by_o NUMBER,
  last_update_date_o DATE,
  synchronization_timestamp_o TIMESTAMP,
  change_type VARCHAR2(20 CHAR) NOT NULL,
  change_version VARCHAR2(50 CHAR),
  change_date DATE NOT NULL
) 
TABLESPACE ositax;