CREATE TABLE sbxtax4.a_contributing_authorities (
  contributing_authority_id NUMBER,
  merchant_id NUMBER,
  authority_id NUMBER,
  this_authority_id NUMBER,
  basis_percent NUMBER(31,10),
  start_date DATE,
  end_date DATE,
  created_by NUMBER,
  creation_date DATE,
  last_updated_by NUMBER,
  last_update_date DATE,
  synchronization_timestamp TIMESTAMP,
  contributing_authority_id_o NUMBER,
  merchant_id_o NUMBER,
  authority_id_o NUMBER,
  this_authority_id_o NUMBER,
  basis_percent_o NUMBER(31,10),
  start_date_o DATE,
  end_date_o DATE,
  created_by_o NUMBER,
  creation_date_o DATE,
  last_updated_by_o NUMBER,
  last_update_date_o DATE,
  synchronization_timestamp_o TIMESTAMP,
  change_type VARCHAR2(20 CHAR) NOT NULL,
  change_version VARCHAR2(50 CHAR),
  change_date DATE
) 
TABLESPACE ositax;