CREATE TABLE sbxtax4.a_rules (
  rule_id NUMBER,
  rule_order NUMBER(31,10),
  auth_report_group_id NUMBER,
  "ACTIVE" VARCHAR2(1 CHAR),
  product_category_id NUMBER,
  merchant_id NUMBER,
  authority_id NUMBER,
  code VARCHAR2(50 CHAR),
  exempt_reason_code VARCHAR2(50 CHAR),
  calculation_method VARCHAR2(50 CHAR),
  invoice_description VARCHAR2(100 CHAR),
  "EXEMPT" VARCHAR2(1 CHAR),
  start_date DATE,
  end_date DATE,
  deleted VARCHAR2(1 CHAR),
  created_by NUMBER,
  creation_date DATE,
  last_updated_by NUMBER,
  last_update_date DATE,
  synchronization_timestamp TIMESTAMP,
  rate_code VARCHAR2(50 CHAR),
  basis_percent NUMBER(31,10),
  rule_comment VARCHAR2(2000 CHAR),
  tax_type VARCHAR2(100 CHAR),
  is_local VARCHAR2(1 CHAR),
  local_authority_type_id NUMBER,
  input_recovery_amount NUMBER(31,5),
  input_recovery_percent NUMBER(31,10),
  unit_of_measure VARCHAR2(100 CHAR),
  no_tax VARCHAR2(1 CHAR),
  reporting_category VARCHAR2(100 CHAR),
  tax_treatment VARCHAR2(100 CHAR),
  is_dependent_product VARCHAR2(1 CHAR),
  material_set_list_id NUMBER,
  authority_rate_set_id NUMBER,
  rule_id_o NUMBER,
  rule_order_o NUMBER(31,10),
  auth_report_group_id_o NUMBER,
  active_o VARCHAR2(1 CHAR),
  product_category_id_o NUMBER,
  merchant_id_o NUMBER,
  authority_id_o NUMBER,
  code_o VARCHAR2(50 CHAR),
  exempt_reason_code_o VARCHAR2(50 CHAR),
  calculation_method_o VARCHAR2(50 CHAR),
  invoice_description_o VARCHAR2(100 CHAR),
  exempt_o VARCHAR2(1 CHAR),
  start_date_o DATE,
  end_date_o DATE,
  deleted_o VARCHAR2(1 CHAR),
  created_by_o NUMBER,
  creation_date_o DATE,
  last_updated_by_o NUMBER,
  last_update_date_o DATE,
  synchronization_timestamp_o TIMESTAMP,
  rate_code_o VARCHAR2(50 CHAR),
  basis_percent_o NUMBER(31,10),
  rule_comment_o VARCHAR2(2000 CHAR),
  tax_type_o VARCHAR2(100 CHAR),
  is_local_o VARCHAR2(1 CHAR),
  local_authority_type_id_o NUMBER,
  input_recovery_amount_o NUMBER(31,5),
  input_recovery_percent_o NUMBER(31,10),
  unit_of_measure_o VARCHAR2(100 CHAR),
  no_tax_o VARCHAR2(1 CHAR),
  reporting_category_o VARCHAR2(100 CHAR),
  tax_treatment_o VARCHAR2(100 CHAR),
  is_dependent_product_o VARCHAR2(1 CHAR),
  material_set_list_id_o NUMBER,
  authority_rate_set_id_o NUMBER,
  change_type VARCHAR2(20 CHAR) NOT NULL,
  change_version VARCHAR2(50 CHAR),
  change_date DATE NOT NULL
) 
TABLESPACE ositax
LOB (rule_comment) STORE AS SECUREFILE (
  ENABLE STORAGE IN ROW)
LOB (rule_comment_o) STORE AS SECUREFILE (
  ENABLE STORAGE IN ROW);