CREATE TABLE sbxtax4.a_rule_qualifiers (
  rule_qualifier_id NUMBER,
  rule_id NUMBER,
  rule_qualifier_type VARCHAR2(50 CHAR),
  "ELEMENT" VARCHAR2(200 CHAR),
  "OPERATOR" VARCHAR2(50 CHAR),
  "VALUE" VARCHAR2(200 CHAR),
  value_type VARCHAR2(50 CHAR),
  element_type VARCHAR2(50 CHAR),
  element_value VARCHAR2(200 CHAR),
  reference_list_id NUMBER,
  authority_id NUMBER,
  start_date DATE,
  end_date DATE,
  created_by NUMBER,
  creation_date DATE,
  last_updated_by NUMBER,
  last_update_date DATE,
  synchronization_timestamp TIMESTAMP,
  rule_qualifier_id_o NUMBER,
  rule_id_o NUMBER,
  rule_qualifier_type_o VARCHAR2(50 CHAR),
  element_o VARCHAR2(200 CHAR),
  operator_o VARCHAR2(50 CHAR),
  value_o VARCHAR2(200 CHAR),
  value_type_o VARCHAR2(50 CHAR),
  element_type_o VARCHAR2(50 CHAR),
  element_value_o VARCHAR2(200 CHAR),
  reference_list_id_o NUMBER,
  authority_id_o NUMBER,
  start_date_o DATE,
  end_date_o DATE,
  created_by_o NUMBER,
  creation_date_o DATE,
  last_updated_by_o NUMBER,
  last_update_date_o DATE,
  synchronization_timestamp_o TIMESTAMP,
  change_type VARCHAR2(20 CHAR) NOT NULL,
  change_version VARCHAR2(50 CHAR),
  change_date DATE NOT NULL
) 
TABLESPACE ositax;