CREATE GLOBAL TEMPORARY TABLE sbxtax4.ct_combined_rates_bu (
  "STATE" VARCHAR2(50 BYTE) NOT NULL,
  county VARCHAR2(100 BYTE) NOT NULL,
  city VARCHAR2(100 BYTE) NOT NULL,
  zip VARCHAR2(5 BYTE) NOT NULL,
  plus4 VARCHAR2(9 BYTE),
  rate NUMBER
)
ON COMMIT PRESERVE ROWS;