CREATE TABLE sbxtax4.ht_rule_qualifiers (
  authority_id NUMBER(10),
  created_by NUMBER(10),
  creation_date DATE,
  "ELEMENT" VARCHAR2(200 BYTE),
  element_type VARCHAR2(50 BYTE),
  element_value VARCHAR2(200 BYTE),
  end_date DATE,
  last_updated_by NUMBER(10),
  last_update_date DATE,
  "OPERATOR" VARCHAR2(50 BYTE),
  reference_list_id NUMBER(10),
  rule_id NUMBER(10),
  rule_qualifier_id NUMBER(10),
  rule_qualifier_type VARCHAR2(50 BYTE),
  start_date DATE,
  synchronization_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
  "VALUE" VARCHAR2(200 BYTE),
  value_type VARCHAR2(50 BYTE),
  aud_rule_qualifier_id NUMBER(10) NOT NULL,
  audit_event_id NUMBER(10) NOT NULL,
  operation_type VARCHAR2(200 BYTE) NOT NULL,
  entity_owner_id NUMBER(10)
) 
TABLESPACE ositax;