CREATE TABLE sbxtax4.plan_table (
  "STATEMENT_ID" VARCHAR2(30 CHAR),
  "TIMESTAMP" DATE,
  remarks VARCHAR2(80 CHAR),
  operation VARCHAR2(30 CHAR),
  options VARCHAR2(30 CHAR),
  object_node VARCHAR2(128 CHAR),
  object_owner VARCHAR2(30 CHAR),
  object_name VARCHAR2(30 CHAR),
  object_instance NUMBER,
  object_type VARCHAR2(30 CHAR),
  optimizer VARCHAR2(255 CHAR),
  search_columns NUMBER,
  "ID" NUMBER,
  parent_id NUMBER,
  position NUMBER,
  "COST" NUMBER,
  "CARDINALITY" NUMBER,
  bytes NUMBER,
  other_tag VARCHAR2(255 CHAR),
  partition_start VARCHAR2(255 CHAR),
  partition_stop VARCHAR2(255 CHAR),
  partition_id NUMBER,
  "OTHER" LONG,
  distribution VARCHAR2(30 CHAR)
) 
TABLESPACE ositax;