CREATE TABLE sbxtax4.tdr_etl_tb_rule_qualifiers (
  rule_qualifier_id NUMBER,
  rule_id NUMBER,
  rule_qualifier_type VARCHAR2(50 CHAR),
  "ELEMENT" VARCHAR2(200 CHAR) NOT NULL,
  "OPERATOR" VARCHAR2(50 CHAR) NOT NULL,
  "VALUE" VARCHAR2(200 CHAR),
  value_type VARCHAR2(50 CHAR),
  element_type VARCHAR2(50 CHAR),
  element_value VARCHAR2(200 CHAR),
  reference_list_id NUMBER(10),
  authority_id NUMBER(10),
  start_date DATE NOT NULL,
  end_date DATE,
  authority VARCHAR2(400 CHAR),
  is_local VARCHAR2(4 CHAR),
  product_category_id NUMBER,
  reference_list_name VARCHAR2(400 CHAR),
  rule_authority_uuid VARCHAR2(36 CHAR),
  rule_order NUMBER,
  rule_start_date DATE,
  nkid NUMBER,
  rid NUMBER
) 
TABLESPACE ositax;