CREATE TABLE sbxtax3.a_rates (
  rate_id NUMBER(10),
  rate_code VARCHAR2(50 BYTE),
  description VARCHAR2(100 BYTE),
  rate NUMBER(31,10),
  flat_fee NUMBER(31,5),
  currency_id NUMBER(10),
  unit_of_measure_code VARCHAR2(25 BYTE),
  use_default_qty VARCHAR2(1 BYTE),
  merchant_id NUMBER(10),
  authority_id NUMBER(10),
  start_date DATE,
  end_date DATE,
  created_by NUMBER(10),
  creation_date DATE,
  last_updated_by NUMBER(10),
  last_update_date DATE,
  split_type VARCHAR2(2 BYTE),
  split_amount_type VARCHAR2(1 BYTE),
  is_local VARCHAR2(1 BYTE),
  rate_id_o NUMBER(10),
  rate_code_o VARCHAR2(50 BYTE),
  description_o VARCHAR2(100 BYTE),
  rate_o NUMBER(31,10),
  flat_fee_o NUMBER(31,5),
  currency_id_o NUMBER(10),
  unit_of_measure_code_o VARCHAR2(25 BYTE),
  use_default_qty_o VARCHAR2(1 BYTE),
  merchant_id_o NUMBER(10),
  authority_id_o NUMBER(10),
  start_date_o DATE,
  end_date_o DATE,
  created_by_o NUMBER(10),
  creation_date_o DATE,
  last_updated_by_o NUMBER(10),
  last_update_date_o DATE,
  split_type_o VARCHAR2(2 BYTE),
  split_amount_type_o VARCHAR2(1 BYTE),
  is_local_o VARCHAR2(1 BYTE),
  change_type VARCHAR2(20 BYTE) NOT NULL,
  change_version VARCHAR2(50 BYTE),
  change_date DATE NOT NULL
) 
TABLESPACE ositax;