CREATE TABLE sbxtax3.a_rule_qualifiers (
  rule_qualifier_id NUMBER(10),
  rule_id NUMBER(10),
  rule_qualifier_type VARCHAR2(50 BYTE),
  "ELEMENT" VARCHAR2(200 BYTE),
  "OPERATOR" VARCHAR2(50 BYTE),
  "VALUE" VARCHAR2(200 BYTE),
  value_type VARCHAR2(50 BYTE),
  element_type VARCHAR2(50 BYTE),
  element_value VARCHAR2(200 BYTE),
  reference_list_id NUMBER(10),
  authority_id NUMBER(10),
  start_date DATE,
  end_date DATE,
  created_by NUMBER(10),
  creation_date DATE,
  last_updated_by NUMBER(10),
  last_update_date DATE,
  rule_qualifier_id_o NUMBER(10),
  rule_id_o NUMBER(10),
  rule_qualifier_type_o VARCHAR2(50 BYTE),
  element_o VARCHAR2(200 BYTE),
  operator_o VARCHAR2(50 BYTE),
  value_o VARCHAR2(200 BYTE),
  value_type_o VARCHAR2(50 BYTE),
  element_type_o VARCHAR2(50 BYTE),
  element_value_o VARCHAR2(200 BYTE),
  reference_list_id_o NUMBER(10),
  authority_id_o NUMBER(10),
  start_date_o DATE,
  end_date_o DATE,
  created_by_o NUMBER(10),
  creation_date_o DATE,
  last_updated_by_o NUMBER(10),
  last_update_date_o DATE,
  change_type VARCHAR2(20 BYTE) NOT NULL,
  change_version VARCHAR2(50 BYTE),
  change_date DATE NOT NULL
) 
TABLESPACE ositax;