CREATE TABLE sbxtax3.a_zones (
  zone_id NUMBER(10),
  "NAME" VARCHAR2(50 BYTE),
  parent_zone_id NUMBER(10),
  tax_parent_zone_id NUMBER(10),
  merchant_id NUMBER(10),
  zone_level_id NUMBER(10),
  eu_zone_as_of_date DATE,
  code_2char VARCHAR2(2 BYTE),
  code_3char VARCHAR2(3 BYTE),
  code_iso VARCHAR2(3 BYTE),
  code_fips VARCHAR2(30 BYTE),
  created_by NUMBER(10),
  creation_date DATE,
  last_updated_by NUMBER(10),
  last_update_date DATE,
  reverse_flag VARCHAR2(1 BYTE),
  terminator_flag VARCHAR2(1 BYTE),
  default_flag VARCHAR2(1 BYTE),
  range_min NUMBER(10),
  range_max NUMBER(10),
  zone_id_o NUMBER(10),
  name_o VARCHAR2(50 BYTE),
  parent_zone_id_o NUMBER(10),
  tax_parent_zone_id_o NUMBER(10),
  merchant_id_o NUMBER(10),
  zone_level_id_o NUMBER(10),
  eu_zone_as_of_date_o DATE,
  code_2char_o VARCHAR2(2 BYTE),
  code_3char_o VARCHAR2(3 BYTE),
  code_iso_o VARCHAR2(3 BYTE),
  code_fips_o VARCHAR2(30 BYTE),
  created_by_o NUMBER(10),
  creation_date_o DATE,
  last_updated_by_o NUMBER(10),
  last_update_date_o DATE,
  reverse_flag_o VARCHAR2(1 BYTE),
  terminator_flag_o VARCHAR2(1 BYTE),
  default_flag_o VARCHAR2(1 BYTE),
  range_min_o NUMBER(10),
  range_max_o NUMBER(10),
  change_type VARCHAR2(20 BYTE) NOT NULL,
  change_version VARCHAR2(50 BYTE),
  change_date DATE NOT NULL,
  eu_exit_date DATE,
  gcc_as_of_date DATE,
  gcc_exit_date DATE,
  eu_exit_date_o DATE,
  gcc_as_of_date_o DATE,
  gcc_exit_date_o DATE
) 
TABLESPACE ositax;