CREATE TABLE sbxtax2.a_app_errors (
  error_id NUMBER(10),
  error_num VARCHAR2(240 BYTE),
  error_severity VARCHAR2(25 BYTE),
  title VARCHAR2(80 BYTE),
  description VARCHAR2(2000 BYTE),
  cause VARCHAR2(2000 BYTE),
  "ACTION" VARCHAR2(2000 BYTE),
  created_by NUMBER(10),
  creation_date DATE,
  last_updated_by NUMBER(10),
  last_update_date DATE,
  "CATEGORY" VARCHAR2(40 BYTE),
  merchant_id NUMBER(10),
  authority_id NUMBER(10),
  error_id_o NUMBER(10),
  error_num_o VARCHAR2(240 BYTE),
  error_severity_o VARCHAR2(25 BYTE),
  title_o VARCHAR2(80 BYTE),
  description_o VARCHAR2(2000 BYTE),
  cause_o VARCHAR2(2000 BYTE),
  action_o VARCHAR2(2000 BYTE),
  created_by_o NUMBER(10),
  creation_date_o DATE,
  last_updated_by_o NUMBER(10),
  last_update_date_o DATE,
  category_o VARCHAR2(40 BYTE),
  merchant_id_o NUMBER(10),
  authority_id_o NUMBER(10),
  change_type VARCHAR2(20 BYTE) NOT NULL,
  change_version VARCHAR2(50 BYTE),
  change_date DATE NOT NULL
) 
TABLESPACE ositax;