CREATE TABLE sbxtax2.a_merchants (
  merchant_id NUMBER(10),
  "ACTIVE" VARCHAR2(1 BYTE),
  "NAME" VARCHAR2(100 BYTE),
  short_name VARCHAR2(10 BYTE),
  legal_entity_name VARCHAR2(200 BYTE),
  merchant_type VARCHAR2(1 BYTE),
  external_token VARCHAR2(36 BYTE),
  notes VARCHAR2(2000 BYTE),
  parent_merchant_id NUMBER(10),
  created_by NUMBER(10),
  xml_error_threshold NUMBER(10),
  xml_group_id NUMBER(10),
  splash_url VARCHAR2(200 BYTE),
  is_content_provider VARCHAR2(1 BYTE),
  b2b_flag VARCHAR2(1 BYTE),
  filter_group_owner_id NUMBER(10),
  filter_group_name VARCHAR2(100 BYTE),
  product_qual_group_owner_id NUMBER(10),
  product_qual_group_name VARCHAR2(100 BYTE),
  tax_code_qual_group_owner_id NUMBER(10),
  tax_code_qual_group_name VARCHAR2(100 BYTE),
  source_system_id VARCHAR2(100 BYTE),
  customer_group_id NUMBER(10),
  uses_exempt_certs VARCHAR2(1 BYTE),
  registration_group_id NUMBER(10),
  create_auto_certs VARCHAR2(1 BYTE),
  create_customers VARCHAR2(1 BYTE),
  days_valid NUMBER(10),
  default_cert_status VARCHAR2(1 BYTE),
  exempt_temp_cert_trans VARCHAR2(1 BYTE),
  us_content_provider_id NUMBER(10),
  intl_content_provider_id NUMBER(10),
  content_version VARCHAR2(20 BYTE),
  content_comment VARCHAR2(50 BYTE),
  content_type VARCHAR2(100 BYTE),
  def_intl_exempt_reason_id NUMBER(10),
  def_us_exempt_reason_id NUMBER(10),
  b2b_create_merchant VARCHAR2(1 BYTE),
  b2b_parent_merchant_id NUMBER(10),
  b2b_use_parent_prefs VARCHAR2(1 BYTE),
  product_cross_ref_group_id NUMBER(10),
  us_established_merchant_id NUMBER(10),
  intl_established_merchant_id NUMBER(10),
  us_custom_data_provider_id NUMBER(10),
  intl_custom_data_provider_id NUMBER(10),
  us_exchange_rate_merchant_id NUMBER(10),
  intl_exchange_rate_merchant_id NUMBER(10),
  allocation_group_owner_id NUMBER(10),
  allocation_group_name VARCHAR2(100 BYTE),
  is_auditing_messages VARCHAR2(1 BYTE),
  audit_message_threshold NUMBER(10),
  us_product_group_id NUMBER(10),
  intl_product_group_id NUMBER(10),
  merchant_id_o NUMBER(10),
  active_o VARCHAR2(1 BYTE),
  name_o VARCHAR2(100 BYTE),
  short_name_o VARCHAR2(10 BYTE),
  legal_entity_name_o VARCHAR2(200 BYTE),
  merchant_type_o VARCHAR2(1 BYTE),
  external_token_o VARCHAR2(36 BYTE),
  notes_o VARCHAR2(2000 BYTE),
  parent_merchant_id_o NUMBER(10),
  xml_error_threshold_o NUMBER(10),
  xml_group_id_o NUMBER(10),
  splash_url_o VARCHAR2(200 BYTE),
  is_content_provider_o VARCHAR2(1 BYTE),
  b2b_flag_o VARCHAR2(1 BYTE),
  filter_group_owner_id_o NUMBER(10),
  filter_group_name_o VARCHAR2(100 BYTE),
  product_qual_group_owner_id_o NUMBER(10),
  product_qual_group_name_o VARCHAR2(100 BYTE),
  tax_code_qual_group_owner_id_o NUMBER(10),
  tax_code_qual_group_name_o VARCHAR2(100 BYTE),
  source_system_id_o VARCHAR2(100 BYTE),
  customer_group_id_o NUMBER(10),
  uses_exempt_certs_o VARCHAR2(1 BYTE),
  registration_group_id_o NUMBER(10),
  create_auto_certs_o VARCHAR2(1 BYTE),
  create_customers_o VARCHAR2(1 BYTE),
  days_valid_o NUMBER(10),
  default_cert_status_o VARCHAR2(1 BYTE),
  exempt_temp_cert_trans_o VARCHAR2(1 BYTE),
  us_content_provider_id_o NUMBER(10),
  intl_content_provider_id_o NUMBER(10),
  content_version_o VARCHAR2(20 BYTE),
  content_comment_o VARCHAR2(50 BYTE),
  content_type_o VARCHAR2(100 BYTE),
  def_intl_exempt_reason_id_o NUMBER(10),
  def_us_exempt_reason_id_o NUMBER(10),
  b2b_create_merchant_o VARCHAR2(1 BYTE),
  b2b_parent_merchant_id_o NUMBER(10),
  b2b_use_parent_prefs_o VARCHAR2(1 BYTE),
  product_cross_ref_group_id_o NUMBER(10),
  us_established_merchant_id_o NUMBER(10),
  intl_established_merchant_id_o NUMBER(10),
  us_custom_data_provider_id_o NUMBER(10),
  intl_custom_data_provider_id_o NUMBER(10),
  us_exchange_rate_merchant_id_o NUMBER(10),
  intl_exchge_rate_merchant_id_o NUMBER(10),
  change_date DATE NOT NULL
) 
TABLESPACE ositax;