CREATE TABLE sbxtax2.a_rules (
  rule_id NUMBER(10),
  rule_order NUMBER(31,10),
  auth_report_group_id NUMBER(10),
  "ACTIVE" VARCHAR2(1 BYTE),
  product_category_id NUMBER(10),
  merchant_id NUMBER(10),
  authority_id NUMBER(10),
  code VARCHAR2(50 BYTE),
  exempt_reason_code VARCHAR2(50 BYTE),
  calculation_method VARCHAR2(50 BYTE),
  invoice_description VARCHAR2(100 BYTE),
  "EXEMPT" VARCHAR2(1 BYTE),
  start_date DATE,
  end_date DATE,
  deleted VARCHAR2(1 BYTE),
  created_by NUMBER(10),
  creation_date DATE,
  last_updated_by NUMBER(10),
  last_update_date DATE,
  rate_code VARCHAR2(50 BYTE),
  basis_percent NUMBER(31,10),
  rule_comment VARCHAR2(2000 BYTE),
  tax_type VARCHAR2(100 BYTE),
  is_local VARCHAR2(1 BYTE),
  local_authority_type_id NUMBER(10),
  input_recovery_amount NUMBER(31,5),
  input_recovery_percent NUMBER(31,10),
  unit_of_measure VARCHAR2(100 BYTE),
  no_tax VARCHAR2(1 BYTE),
  reporting_category VARCHAR2(100 BYTE),
  tax_treatment VARCHAR2(100 BYTE),
  is_dependent_product VARCHAR2(1 BYTE),
  material_set_list_id NUMBER(10),
  authority_rate_set_id NUMBER(10),
  rule_id_o NUMBER(10),
  rule_order_o NUMBER(31,10),
  auth_report_group_id_o NUMBER(10),
  active_o VARCHAR2(1 BYTE),
  product_category_id_o NUMBER(10),
  merchant_id_o NUMBER(10),
  authority_id_o NUMBER(10),
  code_o VARCHAR2(50 BYTE),
  exempt_reason_code_o VARCHAR2(50 BYTE),
  calculation_method_o VARCHAR2(50 BYTE),
  invoice_description_o VARCHAR2(100 BYTE),
  exempt_o VARCHAR2(1 BYTE),
  start_date_o DATE,
  end_date_o DATE,
  deleted_o VARCHAR2(1 BYTE),
  created_by_o NUMBER(10),
  creation_date_o DATE,
  last_updated_by_o NUMBER(10),
  last_update_date_o DATE,
  rate_code_o VARCHAR2(50 BYTE),
  basis_percent_o NUMBER(31,10),
  rule_comment_o VARCHAR2(2000 BYTE),
  tax_type_o VARCHAR2(100 BYTE),
  is_local_o VARCHAR2(1 BYTE),
  local_authority_type_id_o NUMBER(10),
  input_recovery_amount_o NUMBER(31,5),
  input_recovery_percent_o NUMBER(31,10),
  unit_of_measure_o VARCHAR2(100 BYTE),
  no_tax_o VARCHAR2(1 BYTE),
  reporting_category_o VARCHAR2(100 BYTE),
  tax_treatment_o VARCHAR2(100 BYTE),
  is_dependent_product_o VARCHAR2(1 BYTE),
  material_set_list_id_o NUMBER(10),
  authority_rate_set_id_o NUMBER(10),
  change_type VARCHAR2(20 BYTE) NOT NULL,
  change_version VARCHAR2(50 BYTE),
  change_date DATE NOT NULL
) 
TABLESPACE ositax;