CREATE TABLE sbxtax2.ht_customers (
  address_1 VARCHAR2(60 BYTE),
  address_2 VARCHAR2(60 BYTE),
  address_3 VARCHAR2(60 BYTE),
  address_4 VARCHAR2(60 BYTE),
  business_phone VARCHAR2(20 BYTE),
  city VARCHAR2(60 BYTE),
  contact_department VARCHAR2(100 BYTE),
  contact_email VARCHAR2(60 BYTE),
  contact_fax VARCHAR2(20 BYTE),
  contact_name VARCHAR2(60 BYTE),
  contact_phone VARCHAR2(20 BYTE),
  contact_title VARCHAR2(100 BYTE),
  country VARCHAR2(3 BYTE),
  county VARCHAR2(50 BYTE),
  county_code VARCHAR2(3 BYTE),
  created_by NUMBER(10),
  creation_date DATE,
  customer_comment VARCHAR2(2000 BYTE),
  customer_group_id NUMBER(10),
  customer_id NUMBER(10),
  cust_name VARCHAR2(100 BYTE),
  cust_number VARCHAR2(100 BYTE),
  dba_name VARCHAR2(100 BYTE),
  district VARCHAR2(50 BYTE),
  file_id NUMBER(10),
  fully_exempt VARCHAR2(1 BYTE),
  last_updated_by NUMBER(10),
  last_update_date DATE,
  province VARCHAR2(50 BYTE),
  "STATE" VARCHAR2(50 BYTE),
  st_code VARCHAR2(2 BYTE),
  synchronization_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
  zip_code VARCHAR2(50 BYTE),
  aud_customer_id NUMBER(10) NOT NULL,
  audit_event_id NUMBER(10) NOT NULL,
  operation_type VARCHAR2(200 BYTE) NOT NULL,
  entity_owner_id NUMBER(10)
) 
TABLESPACE ositax;