CREATE OR REPLACE TRIGGER crapp_admin."DETERMINATION_REPORTS_ID"
   BEFORE INSERT
   ON crapp_admin.DETERMINATION_REPORTS
   REFERENCING NEW AS new OLD AS old
   FOR EACH ROW
BEGIN
   SELECT crapp_admin.DETERMINATION_REPORTS_ID_SEQ.NEXTVAL
     INTO :new.ID
     FROM DUAL;
END;
/