CREATE TABLE sbxtax.a_compliance_areas (
  compliance_area_id NUMBER(10),
  "NAME" VARCHAR2(500 CHAR),
  compliance_area_uuid VARCHAR2(32 CHAR),
  effective_zone_level_id NUMBER(10),
  associated_area_count NUMBER(10),
  merchant_id NUMBER(10),
  created_by NUMBER(10),
  creation_date DATE,
  last_updated_by NUMBER(10),
  last_update_date DATE,
  start_date DATE,
  end_date DATE,
  compliance_area_id_o NUMBER(10),
  name_o VARCHAR2(500 CHAR),
  compliance_area_uuid_o VARCHAR2(32 CHAR),
  effective_zone_level_id_o NUMBER(10),
  associated_area_count_o NUMBER(10),
  merchant_id_o NUMBER(10),
  created_by_o NUMBER(10),
  creation_date_o DATE,
  last_updated_by_o NUMBER(10),
  last_update_date_o DATE,
  start_date_o DATE,
  end_date_o DATE,
  change_date DATE,
  change_type VARCHAR2(100 CHAR),
  change_version VARCHAR2(50 CHAR)
) 
TABLESPACE ositax;