CREATE TABLE sbxtax.a_rate_tiers (
  rate_tier_id NUMBER,
  rate_id NUMBER,
  rate NUMBER(31,10),
  flat_fee NUMBER(31,10),
  amount_low NUMBER(31,5),
  amount_high NUMBER(31,5),
  rate_code VARCHAR2(50 CHAR),
  created_by NUMBER,
  creation_date DATE,
  last_updated_by NUMBER,
  last_update_date DATE,
  synchronization_timestamp TIMESTAMP,
  rate_tier_id_o NUMBER,
  rate_id_o NUMBER,
  rate_o NUMBER(31,10),
  flat_fee_o NUMBER(31,10),
  amount_low_o NUMBER(31,5),
  amount_high_o NUMBER(31,5),
  rate_code_o VARCHAR2(50 CHAR),
  created_by_o NUMBER,
  creation_date_o DATE,
  last_updated_by_o NUMBER,
  last_update_date_o DATE,
  synchronization_timestamp_o TIMESTAMP,
  change_type VARCHAR2(20 CHAR) NOT NULL,
  change_version VARCHAR2(50 CHAR),
  change_date DATE NOT NULL
) 
TABLESPACE ositax;