CREATE TABLE sbxtax.a_zones (
  zone_id NUMBER,
  "NAME" VARCHAR2(50 CHAR),
  parent_zone_id NUMBER,
  tax_parent_zone_id NUMBER,
  merchant_id NUMBER,
  zone_level_id NUMBER,
  eu_zone_as_of_date DATE,
  code_2char VARCHAR2(2 CHAR),
  code_3char VARCHAR2(3 CHAR),
  code_iso VARCHAR2(3 CHAR),
  code_fips VARCHAR2(30 CHAR),
  created_by NUMBER,
  creation_date DATE,
  last_updated_by NUMBER,
  last_update_date DATE,
  synchronization_timestamp TIMESTAMP,
  reverse_flag VARCHAR2(1 CHAR),
  terminator_flag VARCHAR2(1 CHAR),
  default_flag VARCHAR2(1 CHAR),
  range_min NUMBER,
  range_max NUMBER,
  zone_id_o NUMBER,
  name_o VARCHAR2(50 CHAR),
  parent_zone_id_o NUMBER,
  tax_parent_zone_id_o NUMBER,
  merchant_id_o NUMBER,
  zone_level_id_o NUMBER,
  eu_zone_as_of_date_o DATE,
  code_2char_o VARCHAR2(2 CHAR),
  code_3char_o VARCHAR2(3 CHAR),
  code_iso_o VARCHAR2(3 CHAR),
  code_fips_o VARCHAR2(30 CHAR),
  created_by_o NUMBER,
  creation_date_o DATE,
  last_updated_by_o NUMBER,
  last_update_date_o DATE,
  synchronization_timestamp_o TIMESTAMP,
  reverse_flag_o VARCHAR2(1 CHAR),
  terminator_flag_o VARCHAR2(1 CHAR),
  default_flag_o VARCHAR2(1 CHAR),
  range_min_o NUMBER,
  range_max_o NUMBER,
  change_type VARCHAR2(20 CHAR) NOT NULL,
  change_version VARCHAR2(50 CHAR),
  change_date DATE NOT NULL,
  eu_exit_date DATE,
  gcc_as_of_date DATE,
  gcc_exit_date DATE,
  eu_exit_date_o DATE,
  gcc_as_of_date_o DATE,
  gcc_exit_date_o DATE
) 
TABLESPACE ositax;