CREATE TABLE sbxtax.ct_zone_tree (
  merchant_id NUMBER NOT NULL,
  primary_key NUMBER NOT NULL,
  zone_1_id NUMBER NOT NULL,
  zone_1_name VARCHAR2(50 BYTE) NOT NULL,
  zone_1_level_id VARCHAR2(2 BYTE),
  zone_2_id NUMBER,
  zone_2_name VARCHAR2(50 BYTE),
  zone_2_level_id VARCHAR2(2 BYTE),
  zone_3_id NUMBER,
  zone_3_name VARCHAR2(50 BYTE),
  zone_3_level_id VARCHAR2(2 BYTE),
  zone_4_id NUMBER,
  zone_4_name VARCHAR2(50 BYTE),
  zone_4_level_id VARCHAR2(2 BYTE),
  zone_5_id NUMBER,
  zone_5_name VARCHAR2(50 BYTE),
  zone_5_level_id VARCHAR2(2 BYTE),
  zone_6_id NUMBER,
  zone_6_name VARCHAR2(50 BYTE),
  zone_6_level_id VARCHAR2(2 BYTE),
  zone_7_id NUMBER,
  zone_7_name VARCHAR2(50 BYTE),
  zone_7_level_id VARCHAR2(2 BYTE),
  tax_parent_zone VARCHAR2(50 BYTE),
  eu_zone_as_of_date DATE,
  code_2char VARCHAR2(2 BYTE),
  code_3char VARCHAR2(3 BYTE),
  code_iso VARCHAR2(3 BYTE),
  code_fips VARCHAR2(30 BYTE),
  reverse_flag VARCHAR2(1 BYTE),
  terminator_flag VARCHAR2(1 BYTE),
  default_flag VARCHAR2(1 BYTE),
  range_min NUMBER(10),
  range_max NUMBER(10),
  creation_date DATE,
  zone_8_name VARCHAR2(250 BYTE),
  zone_8_id NUMBER,
  zone_8_level_id NUMBER,
  zone_9_name VARCHAR2(250 BYTE),
  zone_9_id NUMBER,
  zone_9_level_id NUMBER,
  eu_exit_date DATE,
  gcc_as_of_date DATE,
  gcc_exit_date DATE
) 
TABLESPACE ositax;