CREATE TABLE sbxtax.ht_users (
  created_by NUMBER(10),
  creation_date DATE,
  deleted VARCHAR2(1 BYTE),
  email VARCHAR2(60 BYTE),
  end_date DATE,
  extension VARCHAR2(6 BYTE),
  external_token VARCHAR2(36 BYTE),
  first_name VARCHAR2(30 BYTE),
  force_password_change VARCHAR2(1 BYTE),
  java_password VARCHAR2(16 BYTE),
  last_name VARCHAR2(30 BYTE),
  last_updated_by NUMBER(10),
  last_update_date DATE,
  merchant_id NUMBER(10),
  mi VARCHAR2(1 BYTE),
  notes VARCHAR2(240 BYTE),
  password_expiration_date DATE,
  password_never_expires VARCHAR2(1 BYTE),
  phone VARCHAR2(20 BYTE),
  start_date DATE,
  synchronization_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
  username VARCHAR2(60 BYTE),
  user_id NUMBER(10),
  aud_user_id NUMBER(10) NOT NULL,
  audit_event_id NUMBER(10) NOT NULL,
  operation_type VARCHAR2(200 BYTE) NOT NULL,
  entity_owner_id NUMBER(10)
) 
TABLESPACE ositax;