CREATE TABLE sbxtax.ht_zones (
  code_2char VARCHAR2(2 BYTE),
  code_3char VARCHAR2(3 BYTE),
  code_fips VARCHAR2(30 BYTE),
  code_iso VARCHAR2(3 BYTE),
  created_by NUMBER(10),
  creation_date DATE,
  default_flag VARCHAR2(1 BYTE),
  eu_zone_as_of_date DATE,
  last_updated_by NUMBER(10),
  last_update_date DATE,
  merchant_id NUMBER(10),
  "NAME" VARCHAR2(50 BYTE),
  parent_zone_id NUMBER(10),
  range_max NUMBER(10),
  range_min NUMBER(10),
  reverse_flag VARCHAR2(1 BYTE),
  synchronization_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
  tax_parent_zone_id NUMBER(10),
  terminator_flag VARCHAR2(1 BYTE),
  zone_id NUMBER(10),
  zone_level_id NUMBER(10),
  aud_zone_id NUMBER(10) NOT NULL,
  audit_event_id NUMBER(10) NOT NULL,
  operation_type VARCHAR2(200 BYTE) NOT NULL,
  entity_owner_id NUMBER(10),
  eu_exit_date DATE,
  gcc_as_of_date DATE,
  gcc_exit_date DATE
) 
TABLESPACE ositax;