CREATE TABLE sbxtax.tdr_etl_ct_product_tree (
  product_1_name VARCHAR2(500 CHAR),
  product_2_name VARCHAR2(500 CHAR),
  product_3_name VARCHAR2(500 CHAR),
  product_4_name VARCHAR2(500 CHAR),
  product_5_name VARCHAR2(500 CHAR),
  product_6_name VARCHAR2(500 CHAR),
  product_7_name VARCHAR2(500 CHAR),
  product_8_name VARCHAR2(500 CHAR),
  product_9_name VARCHAR2(500 CHAR),
  product_tree VARCHAR2(36 CHAR),
  prodcode VARCHAR2(100 CHAR),
  description VARCHAR2(1000 CHAR),
  nkid NUMBER,
  product_1_nkid NUMBER,
  product_2_nkid NUMBER,
  product_3_nkid NUMBER,
  product_4_nkid NUMBER,
  product_5_nkid NUMBER,
  product_6_nkid NUMBER,
  product_7_nkid NUMBER,
  product_8_nkid NUMBER,
  product_9_nkid NUMBER,
  sort_key VARCHAR2(100 CHAR),
  "NAME" VARCHAR2(500 CHAR),
  product_10_name VARCHAR2(100 CHAR),
  product_10_id NUMBER,
  product_10_nkid NUMBER,
  rid NUMBER
) 
TABLESPACE ositax;