CREATE OR REPLACE TRIGGER sbxtax."DEL_A_ZONES"
  BEFORE DELETE ON sbxtax.TB_ZONES
  REFERENCING FOR EACH ROW
  BEGIN
  IF :OLD.ZONE_LEVEL_ID>-8 THEN 
  INSERT INTO A_ZONES (
ZONE_ID_O,
NAME_O,
PARENT_ZONE_ID_O,
TAX_PARENT_ZONE_ID_O,
MERCHANT_ID_O,
ZONE_LEVEL_ID_O,
EU_ZONE_AS_OF_DATE_O,
CODE_2CHAR_O,
CODE_3CHAR_O,
CODE_ISO_O,
CODE_FIPS_O,
CREATED_BY_O,
CREATION_DATE_O,
LAST_UPDATED_BY_O,
LAST_UPDATE_DATE_O,
--SYNCHRONIZATION_TIMESTAMP_O,
REVERSE_FLAG_O,
TERMINATOR_FLAG_O,
DEFAULT_FLAG_O,
RANGE_MIN_O,
RANGE_MAX_O,
EU_EXIT_DATE_O,
GCC_AS_OF_DATE_O,
GCC_EXIT_DATE_O,
CHANGE_TYPE,
--CHANGE_VERSION,
CHANGE_DATE
  ) VALUES (
:OLD.ZONE_ID,
:OLD.NAME,
:OLD.PARENT_ZONE_ID,
:OLD.TAX_PARENT_ZONE_ID,
:OLD.MERCHANT_ID,
:OLD.ZONE_LEVEL_ID,
:OLD.EU_ZONE_AS_OF_DATE,
:OLD.CODE_2CHAR,
:OLD.CODE_3CHAR,
:OLD.CODE_ISO,
:OLD.CODE_FIPS,
:OLD.CREATED_BY,
:OLD.CREATION_DATE,
:OLD.LAST_UPDATED_BY,
:OLD.LAST_UPDATE_DATE,
--:OLD.SYNCHRONIZATION_TIMESTAMP,
:OLD.REVERSE_FLAG,
:OLD.TERMINATOR_FLAG,
:OLD.DEFAULT_FLAG,
:OLD.RANGE_MIN,
:OLD.RANGE_MAX,
:OLD.EU_EXIT_DATE,
:OLD.GCC_AS_OF_DATE,
:OLD.GCC_EXIT_DATE,
    'DELETED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS M WHERE M.MERCHANT_ID = :OLD.MERCHANT_ID),
    SYSDATE);
    END IF;--ONLY UPDATE/INSERT/DELETE IF ABOVE A CITY LEVEL
END;
/