CREATE OR REPLACE TRIGGER sbxtax."DEL_A_COMPLIANCE_AREAS"
BEFORE DELETE ON sbxtax.TB_COMPLIANCE_AREAS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  INSERT INTO A_COMPLIANCE_AREAS (
   COMPLIANCE_AREA_ID_O,
NAME_O,
COMPLIANCE_AREA_UUID_O,
EFFECTIVE_ZONE_LEVEL_ID_O,
ASSOCIATED_AREA_COUNT_O,
MERCHANT_ID_O,
CREATED_BY_O,
CREATION_DATE_O,
LAST_UPDATED_BY_O,
LAST_UPDATE_DATE_O,
START_DATE_O,
END_DATE_O,
    CHANGE_TYPE,
    --CHANGE_VERSION,
    CHANGE_DATE
  ) VALUES (
   :OLD.COMPLIANCE_AREA_ID,
:OLD.NAME,
:OLD.COMPLIANCE_AREA_UUID,
:OLD.EFFECTIVE_ZONE_LEVEL_ID,
:OLD.ASSOCIATED_AREA_COUNT,
:OLD.MERCHANT_ID,
:OLD.CREATED_BY,
:OLD.CREATION_DATE,
:OLD.LAST_UPDATED_BY,
:OLD.LAST_UPDATE_DATE,
--:OLD.SYNCHRONIZATION_TIMESTAMP,
:OLD.START_DATE,
:OLD.END_DATE,
    'DELETED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS WHERE MERCHANT_ID = :OLD.MERCHANT_ID),
    SYSDATE);
END;
/