CREATE OR REPLACE TRIGGER sbxtax."DEL_A_RULE_QUALIFIERS"
BEFORE DELETE ON sbxtax.TB_RULE_QUALIFIERS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  INSERT INTO A_RULE_QUALIFIERS (
RULE_QUALIFIER_ID_O,
RULE_ID_O,
RULE_QUALIFIER_TYPE_O,
ELEMENT_O,
OPERATOR_O,
VALUE_O,
VALUE_TYPE_O,
ELEMENT_TYPE_O,
ELEMENT_VALUE_O,
REFERENCE_LIST_ID_O,
AUTHORITY_ID_O,
START_DATE_O,
END_DATE_O,
CREATED_BY_O,
CREATION_DATE_O,
LAST_UPDATED_BY_O,
LAST_UPDATE_DATE_O,
--SYNCHRONIZATION_TIMESTAMP_O,
CHANGE_TYPE,
--CHANGE_VERSION,
CHANGE_DATE
  ) VALUES (
:OLD.RULE_QUALIFIER_ID,
:OLD.RULE_ID,
:OLD.RULE_QUALIFIER_TYPE,
:OLD.ELEMENT,
:OLD.OPERATOR,
:OLD.VALUE,
:OLD.VALUE_TYPE,
:OLD.ELEMENT_TYPE,
:OLD.ELEMENT_VALUE,
:OLD.REFERENCE_LIST_ID,
:OLD.AUTHORITY_ID,
:OLD.START_DATE,
:OLD.END_DATE,
:OLD.CREATED_BY,
:OLD.CREATION_DATE,
:OLD.LAST_UPDATED_BY,
:OLD.LAST_UPDATE_DATE,
--:OLD.SYNCHRONIZATION_TIMESTAMP,
    'DELETED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS M, TB_RULES RU WHERE M.MERCHANT_ID = RU.MERCHANT_ID AND RU.RULE_ID = :OLD.RULE_ID),
    SYSDATE);
END;
/