CREATE OR REPLACE TRIGGER sbxtax."INS_A_COMPLIANCE_AREAS"
AFTER INSERT ON sbxtax.TB_COMPLIANCE_AREAS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  INSERT INTO A_COMPLIANCE_AREAS (
   COMPLIANCE_AREA_ID,
NAME,
COMPLIANCE_AREA_UUID,
EFFECTIVE_ZONE_LEVEL_ID,
ASSOCIATED_AREA_COUNT,
MERCHANT_ID,
CREATED_BY,
CREATION_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
START_DATE,
END_DATE,
    CHANGE_TYPE,
    --CHANGE_VERSION,
    CHANGE_DATE
  ) VALUES (
    :NEW.COMPLIANCE_AREA_ID,
:NEW.NAME,
:NEW.COMPLIANCE_AREA_UUID,
:NEW.EFFECTIVE_ZONE_LEVEL_ID,
:NEW.ASSOCIATED_AREA_COUNT,
:NEW.MERCHANT_ID,
:NEW.CREATED_BY,
:NEW.CREATION_DATE,
:NEW.LAST_UPDATED_BY,
:NEW.LAST_UPDATE_DATE,
:NEW.START_DATE,
:NEW.END_DATE,
    'CREATED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS WHERE MERCHANT_ID = :NEW.MERCHANT_ID),
    SYSDATE);
END;
/