CREATE OR REPLACE TRIGGER sbxtax."INS_A_RULE_QUALIFIERS"
AFTER INSERT ON sbxtax.TB_RULE_QUALIFIERS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  INSERT INTO A_RULE_QUALIFIERS (
RULE_QUALIFIER_ID,
RULE_ID,
RULE_QUALIFIER_TYPE,
ELEMENT,
OPERATOR,
VALUE,
VALUE_TYPE,
ELEMENT_TYPE,
ELEMENT_VALUE,
REFERENCE_LIST_ID,
AUTHORITY_ID,
START_DATE,
END_DATE,
CREATED_BY,
CREATION_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
--SYNCHRONIZATION_TIMESTAMP,
CHANGE_TYPE,
--CHANGE_VERSION,
CHANGE_DATE
  ) VALUES (
:NEW.RULE_QUALIFIER_ID,
:NEW.RULE_ID,
:NEW.RULE_QUALIFIER_TYPE,
:NEW.ELEMENT,
:NEW.OPERATOR,
:NEW.VALUE,
:NEW.VALUE_TYPE,
:NEW.ELEMENT_TYPE,
:NEW.ELEMENT_VALUE,
:NEW.REFERENCE_LIST_ID,
:NEW.AUTHORITY_ID,
:NEW.START_DATE,
:NEW.END_DATE,
:NEW.CREATED_BY,
:NEW.CREATION_DATE,
:NEW.LAST_UPDATED_BY,
:NEW.LAST_UPDATE_DATE,
--:NEW.SYNCHRONIZATION_TIMESTAMP,
    'CREATED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS M, TB_RULES RU WHERE M.MERCHANT_ID = RU.MERCHANT_ID AND RU.RULE_ID = :NEW.RULE_ID),
    SYSDATE);
END;
/