CREATE OR REPLACE TRIGGER sbxtax."INS_A_APP_ERRORS"
AFTER INSERT ON sbxtax.TB_APP_ERRORS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  INSERT INTO A_APP_ERRORS (
ERROR_ID,
ERROR_NUM,
ERROR_SEVERITY,
TITLE,
DESCRIPTION,
CAUSE,
ACTION,
CREATED_BY,
CREATION_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
--SYNCHRONIZATION_TIMESTAMP,
CATEGORY,
MERCHANT_ID,
AUTHORITY_ID,
CHANGE_TYPE,
--CHANGE_VERSION,
CHANGE_DATE
  ) VALUES (
:NEW.ERROR_ID,
:NEW.ERROR_NUM,
:NEW.ERROR_SEVERITY,
:NEW.TITLE,
:NEW.DESCRIPTION,
:NEW.CAUSE,
:NEW.ACTION,
:NEW.CREATED_BY,
:NEW.CREATION_DATE,
:NEW.LAST_UPDATED_BY,
:NEW.LAST_UPDATE_DATE,
--:NEW.SYNCHRONIZATION_TIMESTAMP,
:NEW.CATEGORY,
:NEW.MERCHANT_ID,
:NEW.AUTHORITY_ID,

    'CREATED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS WHERE MERCHANT_ID = :NEW.MERCHANT_ID),
    SYSDATE);
END;
/