CREATE OR REPLACE TRIGGER sbxtax."INS_A_RATES"
AFTER INSERT ON sbxtax.TB_RATES
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  INSERT INTO A_RATES (
    RATE_ID,
    RATE_CODE,
    DESCRIPTION,
    RATE,
    FLAT_FEE,
    CURRENCY_ID,
    UNIT_OF_MEASURE_CODE,
    USE_DEFAULT_QTY,
    MERCHANT_ID,
    AUTHORITY_ID,
    START_DATE,
    END_DATE,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    --SYNCHRONIZATION_TIMESTAMP,
    SPLIT_TYPE,
    SPLIT_AMOUNT_TYPE,
    IS_LOCAL,
    CHANGE_TYPE,
    --CHANGE_VERSION,
    CHANGE_DATE
  ) VALUES (
    :NEW.RATE_ID,
    :NEW.RATE_CODE,
    :NEW.DESCRIPTION,
    :NEW.RATE,
    :NEW.FLAT_FEE,
    :NEW.CURRENCY_ID,
    :NEW.UNIT_OF_MEASURE_CODE,
    :NEW.USE_DEFAULT_QTY,
    :NEW.MERCHANT_ID,
    :NEW.AUTHORITY_ID,
    :NEW.START_DATE,
    :NEW.END_DATE,
    :NEW.CREATED_BY,
    :NEW.CREATION_DATE,
    :NEW.LAST_UPDATED_BY,
    :NEW.LAST_UPDATE_DATE,
    --:NEW.SYNCHRONIZATION_TIMESTAMP,
    :NEW.SPLIT_TYPE,
    :NEW.SPLIT_AMOUNT_TYPE,
    :NEW.IS_LOCAL,
    'CREATED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS M WHERE M.MERCHANT_ID = :NEW.MERCHANT_ID),
    SYSDATE);
END;
/