CREATE OR REPLACE TRIGGER sbxtax."UPD_A_ZONE_MATCH_PATTERNS"
AFTER UPDATE OF
    PATTERN,
    VALUE,
    TYPE,
    MERCHANT_ID
    ON sbxtax.TB_ZONE_MATCH_PATTERNS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
     WHEN (
(
decode(NEW.PATTERN,OLD.PATTERN,0,1) +
decode(NEW.VALUE,OLD.VALUE,0,1) +
decode(NEW.TYPE,OLD.TYPE,0,1) +
decode(NEW.MERCHANT_ID,OLD.MERCHANT_ID,0,1)
) > 0
) BEGIN
  INSERT INTO A_ZONE_MATCH_PATTERNS (
  ZONE_MATCH_PATTERN_ID,
    PATTERN,
    VALUE,
    TYPE,
    MERCHANT_ID,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    --SYNCHRONIZATION_TIMESTAMP,
    PATTERN_O,
    ZONE_MATCH_PATTERN_ID_O,
    VALUE_O,
    TYPE_O,
    MERCHANT_ID_O,
    CREATED_BY_O,
    CREATION_DATE_O,
    LAST_UPDATED_BY_O,
    LAST_UPDATE_DATE_O,
    --SYNCHRONIZATION_TIMESTAMP_O,
    --CHANGE_VERSION,
    CHANGE_TYPE,
    CHANGE_DATE
  ) VALUES (
   :NEW.ZONE_MATCH_PATTERN_ID,
  :NEW.PATTERN,
  :NEW.VALUE,
  :NEW.TYPE,
  :NEW.MERCHANT_ID,
  :NEW.CREATED_BY,
  :NEW.CREATION_DATE,
  :NEW.LAST_UPDATED_BY,
  :NEW.LAST_UPDATE_DATE,
  :OLD.ZONE_MATCH_PATTERN_ID,
  :OLD.PATTERN,
  :OLD.VALUE,
  :OLD.TYPE,
  :OLD.MERCHANT_ID,
  :OLD.CREATED_BY,
  :OLD.CREATION_DATE,
  :OLD.LAST_UPDATED_BY,
  :OLD.LAST_UPDATE_DATE,
    'UPDATED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS M WHERE M.MERCHANT_ID = :NEW.MERCHANT_ID),
    SYSDATE);
END;
/