CREATE OR REPLACE TRIGGER sbxtax."UPD_A_CONTRIBUTING_AUTHORITIES"
AFTER UPDATE OF
MERCHANT_ID,
AUTHORITY_ID,
THIS_AUTHORITY_ID,
BASIS_PERCENT,
START_DATE,
END_DATE
ON sbxtax.TB_CONTRIBUTING_AUTHORITIES
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
     WHEN (
(
decode(NEW.MERCHANT_ID,OLD.MERCHANT_ID,0,1) +
decode(NEW.AUTHORITY_ID,OLD.AUTHORITY_ID,0,1) +
decode(NEW.THIS_AUTHORITY_ID,OLD.THIS_AUTHORITY_ID,0,1) +
decode(NEW.BASIS_PERCENT,OLD.BASIS_PERCENT,0,1) +
decode(NEW.START_DATE,OLD.START_DATE,0,1) +
decode(NEW.END_DATE,OLD.END_DATE,0,1)
) > 0
) BEGIN
  INSERT INTO A_CONTRIBUTING_AUTHORITIES (
CONTRIBUTING_AUTHORITY_ID,
MERCHANT_ID,
AUTHORITY_ID,
THIS_AUTHORITY_ID,
BASIS_PERCENT,
START_DATE,
END_DATE,
CREATED_BY,
CREATION_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
--SYNCHRONIZATION_TIMESTAMP,
CONTRIBUTING_AUTHORITY_ID_O,
MERCHANT_ID_O,
AUTHORITY_ID_O,
THIS_AUTHORITY_ID_O,
BASIS_PERCENT_O,
START_DATE_O,
END_DATE_O,
CREATED_BY_O,
CREATION_DATE_O,
LAST_UPDATED_BY_O,
LAST_UPDATE_DATE_O,
--SYNCHRONIZATION_TIMESTAMP_O,
CHANGE_TYPE,
--CHANGE_VERSION,
CHANGE_DATE
  ) VALUES (
:NEW.CONTRIBUTING_AUTHORITY_ID,
:NEW.MERCHANT_ID,
:NEW.AUTHORITY_ID,
:NEW.THIS_AUTHORITY_ID,
:NEW.BASIS_PERCENT,
:NEW.START_DATE,
:NEW.END_DATE,
:NEW.CREATED_BY,
:NEW.CREATION_DATE,
:NEW.LAST_UPDATED_BY,
:NEW.LAST_UPDATE_DATE,
--:NEW.SYNCHRONIZATION_TIMESTAMP,
:OLD.CONTRIBUTING_AUTHORITY_ID,
:OLD.MERCHANT_ID,
:OLD.AUTHORITY_ID,
:OLD.THIS_AUTHORITY_ID,
:OLD.BASIS_PERCENT,
:OLD.START_DATE,
:OLD.END_DATE,
:OLD.CREATED_BY,
:OLD.CREATION_DATE,
:OLD.LAST_UPDATED_BY,
:OLD.LAST_UPDATE_DATE,
--:OLD.SYNCHRONIZATION_TIMESTAMP,
    'UPDATED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS WHERE MERCHANT_ID = :NEW.MERCHANT_ID),
    SYSDATE);
END;
/