CREATE OR REPLACE TRIGGER sbxtax4."INS_A_RATE_TIERS"
AFTER INSERT ON sbxtax4.TB_RATE_TIERS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  INSERT INTO A_RATE_TIERS (
    RATE_TIER_ID,
    RATE_ID,
    RATE,
    FLAT_FEE,
    AMOUNT_LOW,
    AMOUNT_HIGH,
    RATE_CODE,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    --SYNCHRONIZATION_TIMESTAMP,
    CHANGE_TYPE,
    --CHANGE_VERSION,
    CHANGE_DATE
  ) VALUES (
    :NEW.RATE_TIER_ID,
    :NEW.RATE_ID,
    :NEW.RATE,
    :NEW.FLAT_FEE,
    :NEW.AMOUNT_LOW,
    :NEW.AMOUNT_HIGH,
    :NEW.RATE_CODE,
    :NEW.CREATED_BY,
    :NEW.CREATION_DATE,
    :NEW.LAST_UPDATED_BY,
    :NEW.LAST_UPDATE_DATE,
    --:NEW.SYNCHRONIZATION_TIMESTAMP,

    'CREATED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS M, TB_RATES R WHERE M.MERCHANT_ID = R.MERCHANT_ID AND R.RATE_ID = :NEW.RATE_ID),
    SYSDATE);
END;
/