CREATE OR REPLACE TRIGGER sbxtax4."INS_A_PRODUCT_CATEGORIES"
AFTER INSERT ON sbxtax4.TB_PRODUCT_CATEGORIES
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
BEGIN
  INSERT INTO A_PRODUCT_CATEGORIES (
PRODUCT_CATEGORY_ID,
PRODUCT_GROUP_ID,
NAME,
DESCRIPTION,
NOTC,
PARENT_PRODUCT_CATEGORY_ID,
MERCHANT_ID,
PRODCODE,
CREATED_BY,
CREATION_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
--SYNCHRONIZATION_TIMESTAMP,
CHANGE_TYPE,
--CHANGE_VERSION,
CHANGE_DATE
  ) VALUES (
:NEW.PRODUCT_CATEGORY_ID,
:NEW.PRODUCT_GROUP_ID,
:NEW.NAME,
:NEW.DESCRIPTION,
:NEW.NOTC,
:NEW.PARENT_PRODUCT_CATEGORY_ID,
:NEW.MERCHANT_ID,
:NEW.PRODCODE,
:NEW.CREATED_BY,
:NEW.CREATION_DATE,
:NEW.LAST_UPDATED_BY,
:NEW.LAST_UPDATE_DATE,
--:NEW.SYNCHRONIZATION_TIMESTAMP,
    'CREATED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS WHERE MERCHANT_ID = :NEW.MERCHANT_ID),
    SYSDATE);
END;
/