CREATE OR REPLACE TRIGGER sbxtax4."UPD_A_PRODUCT_CATEGORIES"
AFTER UPDATE OF
PRODUCT_GROUP_ID,
NAME,
DESCRIPTION,
NOTC,
PARENT_PRODUCT_CATEGORY_ID,
MERCHANT_ID,
PRODCODE
ON sbxtax4.TB_PRODUCT_CATEGORIES
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
      WHEN (
(
decode(NEW.PRODUCT_GROUP_ID,OLD.PRODUCT_GROUP_ID,0,1) +
decode(NEW.NAME,OLD.NAME,0,1) +
decode(NEW.DESCRIPTION,OLD.DESCRIPTION,0,1) +
decode(NEW.NOTC,OLD.NOTC,0,1) +
decode(NEW.PARENT_PRODUCT_CATEGORY_ID,OLD.PARENT_PRODUCT_CATEGORY_ID,0,1) +
decode(NEW.MERCHANT_ID,OLD.MERCHANT_ID,0,1) +
decode(NEW.PRODCODE,OLD.PRODCODE,0,1)
) > 0
) BEGIN
  INSERT INTO A_PRODUCT_CATEGORIES (
PRODUCT_CATEGORY_ID,
PRODUCT_GROUP_ID,
NAME,
DESCRIPTION,
NOTC,
PARENT_PRODUCT_CATEGORY_ID,
MERCHANT_ID,
PRODCODE,
CREATED_BY,
CREATION_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
--SYNCHRONIZATION_TIMESTAMP,
PRODUCT_CATEGORY_ID_O,
PRODUCT_GROUP_ID_O,
NAME_O,
DESCRIPTION_O,
NOTC_O,
PARENT_PRODUCT_CATEGORY_ID_O,
MERCHANT_ID_O,
PRODCODE_O,
CREATED_BY_O,
CREATION_DATE_O,
LAST_UPDATED_BY_O,
LAST_UPDATE_DATE_O,
--SYNCHRONIZATION_TIMESTAMP_O,
CHANGE_TYPE,
--CHANGE_VERSION,
CHANGE_DATE
  ) VALUES (
:NEW.PRODUCT_CATEGORY_ID,
:NEW.PRODUCT_GROUP_ID,
:NEW.NAME,
:NEW.DESCRIPTION,
:NEW.NOTC,
:NEW.PARENT_PRODUCT_CATEGORY_ID,
:NEW.MERCHANT_ID,
:NEW.PRODCODE,
:NEW.CREATED_BY,
:NEW.CREATION_DATE,
:NEW.LAST_UPDATED_BY,
:NEW.LAST_UPDATE_DATE,
--:NEW.SYNCHRONIZATION_TIMESTAMP,
:OLD.PRODUCT_CATEGORY_ID,
:OLD.PRODUCT_GROUP_ID,
:OLD.NAME,
:OLD.DESCRIPTION,
:OLD.NOTC,
:OLD.PARENT_PRODUCT_CATEGORY_ID,
:OLD.MERCHANT_ID,
:OLD.PRODCODE,
:OLD.CREATED_BY,
:OLD.CREATION_DATE,
:OLD.LAST_UPDATED_BY,
:OLD.LAST_UPDATE_DATE,
--:OLD.SYNCHRONIZATION_TIMESTAMP,
    'UPDATED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS WHERE MERCHANT_ID = :NEW.MERCHANT_ID),
    SYSDATE);
END;
/