CREATE OR REPLACE TRIGGER sbxtax4."UPD_A_ZONE_MATCH_CONTEXTS"
AFTER UPDATE OF
ZONE_MATCH_PATTERN_ID,
ZONE_LEVEL_ID,
ZONE_ID
ON sbxtax4.TB_ZONE_MATCH_CONTEXTS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
      WHEN (
(
decode(NEW.ZONE_MATCH_PATTERN_ID,OLD.ZONE_MATCH_PATTERN_ID,0,1) +
decode(NEW.ZONE_LEVEL_ID,OLD.ZONE_LEVEL_ID,0,1) +
decode(NEW.ZONE_ID,OLD.ZONE_ID,0,1)
) > 0
) BEGIN
  INSERT INTO A_ZONE_MATCH_CONTEXTS (
 ZONE_MATCH_CONTEXT_ID,
ZONE_MATCH_PATTERN_ID,
ZONE_LEVEL_ID,
ZONE_ID,
CREATED_BY,
CREATION_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
ZONE_MATCH_CONTEXT_ID_O,
ZONE_MATCH_PATTERN_ID_O,
ZONE_LEVEL_ID_O,
ZONE_ID_O,
CREATED_BY_O,
CREATION_DATE_O,
LAST_UPDATED_BY_O,
LAST_UPDATE_DATE_O,
CHANGE_TYPE ,
CHANGE_DATE
  ) VALUES (
:NEW.ZONE_MATCH_CONTEXT_ID,
:NEW.ZONE_MATCH_PATTERN_ID,
:NEW.ZONE_LEVEL_ID,
:NEW.ZONE_ID,
:NEW.CREATED_BY,
:NEW.CREATION_DATE,
:NEW.LAST_UPDATED_BY,
:NEW.LAST_UPDATE_DATE,
:OLD.ZONE_MATCH_CONTEXT_ID,
:OLD.ZONE_MATCH_PATTERN_ID,
:OLD.ZONE_LEVEL_ID,
:OLD.ZONE_ID,
:OLD.CREATED_BY,
:OLD.CREATION_DATE,
:OLD.LAST_UPDATED_BY,
:OLD.LAST_UPDATE_DATE,
    'UPDATED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS M, TB_RATES R WHERE M.MERCHANT_ID = R.MERCHANT_ID AND R.RATE_ID = :NEW.RATE_ID),
    SYSDATE);
END;
/