CREATE OR REPLACE TRIGGER sbxtax4."UPD_A_AUTHORITIES"
AFTER UPDATE of
    PRODUCT_GROUP_ID,
    NAME,
    UUID,
    INVOICE_DESCRIPTION,
    DESCRIPTION,
    MERCHANT_ID,
    REGION_CODE,
    REGISTRATION_MASK,
    SIMPLE_REGISTRATION_MASK,
    ADMIN_ZONE_LEVEL_ID,
    EFFECTIVE_ZONE_LEVEL_ID,
    AUTHORITY_TYPE_ID,
    LOCATION_CODE,
    DISTANCE_SALES_THRESHOLD,
    ERP_TAX_CODE,
    CONTENT_TYPE,
    UNIT_OF_MEASURE_CODE,
    OFFICIAL_NAME,
    AUTHORITY_CATEGORY ON sbxtax4.TB_AUTHORITIES
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
      WHEN (
  ( decode(NEW.AUTHORITY_CATEGORY,OLD.AUTHORITY_CATEGORY,0,1) +
decode(NEW.OFFICIAL_NAME,OLD.OFFICIAL_NAME,0,1) +
decode(NEW.UNIT_OF_MEASURE_CODE,OLD.UNIT_OF_MEASURE_CODE,0,1) +
decode(NEW.CONTENT_TYPE,OLD.CONTENT_TYPE,0,1) +
decode(NEW.ERP_TAX_CODE,OLD.ERP_TAX_CODE,0,1) +
decode(NEW.IS_CUSTOM_AUTHORITY,OLD.IS_CUSTOM_AUTHORITY,0,1) +
decode(NEW.IS_TEMPLATE,OLD.IS_TEMPLATE,0,1) +
decode(NEW.DISTANCE_SALES_THRESHOLD,OLD.DISTANCE_SALES_THRESHOLD,0,1) +
decode(NEW.LOCATION_CODE,OLD.LOCATION_CODE,0,1) +
decode(NEW.AUTHORITY_TYPE_ID,OLD.AUTHORITY_TYPE_ID,0,1) +
decode(NEW.EFFECTIVE_ZONE_LEVEL_ID,OLD.EFFECTIVE_ZONE_LEVEL_ID,0,1) +
decode(NEW.ADMIN_ZONE_LEVEL_ID,OLD.ADMIN_ZONE_LEVEL_ID,0,1) +
decode(NEW.SIMPLE_REGISTRATION_MASK,OLD.SIMPLE_REGISTRATION_MASK,0,1) +
decode(NEW.REGISTRATION_MASK,OLD.REGISTRATION_MASK,0,1) +
decode(NEW.REGION_CODE,OLD.REGION_CODE,0,1) +
decode(NEW.MERCHANT_ID,OLD.MERCHANT_ID,0,1) +
decode(NEW.DESCRIPTION,OLD.DESCRIPTION,0,1) +
decode(NEW.INVOICE_DESCRIPTION,OLD.INVOICE_DESCRIPTION,0,1) +
decode(NEW.UUID,OLD.UUID,0,1) +
decode(NEW.NAME,OLD.NAME,0,1) +
decode(NEW.PRODUCT_GROUP_ID,OLD.PRODUCT_GROUP_ID,0,1) +
decode(NEW.AUTHORITY_ID,OLD.AUTHORITY_ID,0,1)
  ) > 0

) BEGIN


  INSERT INTO A_AUTHORITIES (
    AUTHORITY_ID,
    PRODUCT_GROUP_ID,
    NAME,
    UUID,
    INVOICE_DESCRIPTION,
    DESCRIPTION,
    MERCHANT_ID,
    REGION_CODE,
    REGISTRATION_MASK,
    SIMPLE_REGISTRATION_MASK,
    CREATED_BY,
    CREATION_DATE,
    LAST_UPDATED_BY,
    LAST_UPDATE_DATE,
    --SYNCHRONIZATION_TIMESTAMP,
    ADMIN_ZONE_LEVEL_ID,
    EFFECTIVE_ZONE_LEVEL_ID,
    AUTHORITY_TYPE_ID,
    LOCATION_CODE,
    DISTANCE_SALES_THRESHOLD,
    IS_TEMPLATE,
    IS_CUSTOM_AUTHORITY,
    ERP_TAX_CODE,
    CONTENT_TYPE,
    UNIT_OF_MEASURE_CODE,
    OFFICIAL_NAME,
    AUTHORITY_CATEGORY,
    AUTHORITY_ID_O,
    PRODUCT_GROUP_ID_O,
    NAME_O,
    UUID_O,
    INVOICE_DESCRIPTION_O,
    DESCRIPTION_O,
    MERCHANT_ID_O,
    REGION_CODE_O,
    REGISTRATION_MASK_O,
    SIMPLE_REGISTRATION_MASK_O,
    CREATED_BY_O,
    CREATION_DATE_O,
    LAST_UPDATED_BY_O,
    LAST_UPDATE_DATE_O,
    --SYNCHRONIZATION_TIMESTAMP_O,
    ADMIN_ZONE_LEVEL_ID_O,
    EFFECTIVE_ZONE_LEVEL_ID_O,
    AUTHORITY_TYPE_ID_O,
    LOCATION_CODE_O,
    DISTANCE_SALES_THRESHOLD_O,
    IS_TEMPLATE_O,
    IS_CUSTOM_AUTHORITY_O,
    ERP_TAX_CODE_O,
    CONTENT_TYPE_O,
    UNIT_OF_MEASURE_CODE_O,
    OFFICIAL_NAME_O,
    AUTHORITY_CATEGORY_O,
    CHANGE_TYPE,
    --CHANGE_VERSION,
    CHANGE_DATE
  ) VALUES (
    :NEW.AUTHORITY_ID,
    :NEW.PRODUCT_GROUP_ID,
    :NEW.NAME,
    :NEW.UUID,
    :NEW.INVOICE_DESCRIPTION,
    :NEW.DESCRIPTION,
    :NEW.MERCHANT_ID,
    :NEW.REGION_CODE,
    :NEW.REGISTRATION_MASK,
    :NEW.SIMPLE_REGISTRATION_MASK,
    :NEW.CREATED_BY,
    :NEW.CREATION_DATE,
    :NEW.LAST_UPDATED_BY,
    :NEW.LAST_UPDATE_DATE,
    --:NEW.SYNCHRONIZATION_TIMESTAMP,
    :NEW.ADMIN_ZONE_LEVEL_ID,
    :NEW.EFFECTIVE_ZONE_LEVEL_ID,
    :NEW.AUTHORITY_TYPE_ID,
    :NEW.LOCATION_CODE,
    :NEW.DISTANCE_SALES_THRESHOLD,
    :NEW.IS_TEMPLATE,
    :NEW.IS_CUSTOM_AUTHORITY,
    :NEW.ERP_TAX_CODE,
    :NEW.CONTENT_TYPE,
    :NEW.UNIT_OF_MEASURE_CODE,
    :NEW.OFFICIAL_NAME,
    :NEW.AUTHORITY_CATEGORY,
    :OLD.AUTHORITY_ID,
    :OLD.PRODUCT_GROUP_ID,
    :OLD.NAME,
    :OLD.UUID,
    :OLD.INVOICE_DESCRIPTION,
    :OLD.DESCRIPTION,
    :OLD.MERCHANT_ID,
    :OLD.REGION_CODE,
    :OLD.REGISTRATION_MASK,
    :OLD.SIMPLE_REGISTRATION_MASK,
    :OLD.CREATED_BY,
    :OLD.CREATION_DATE,
    :OLD.LAST_UPDATED_BY,
    :OLD.LAST_UPDATE_DATE,
    --:OLD.SYNCHRONIZATION_TIMESTAMP,
    :OLD.ADMIN_ZONE_LEVEL_ID,
    :OLD.EFFECTIVE_ZONE_LEVEL_ID,
    :OLD.AUTHORITY_TYPE_ID,
    :OLD.LOCATION_CODE,
    :OLD.DISTANCE_SALES_THRESHOLD,
    :OLD.IS_TEMPLATE,
    :OLD.IS_CUSTOM_AUTHORITY,
    :OLD.ERP_TAX_CODE,
    :OLD.CONTENT_TYPE,
    :OLD.UNIT_OF_MEASURE_CODE,
    :OLD.OFFICIAL_NAME,
    :OLD.AUTHORITY_CATEGORY,
    'UPDATED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS WHERE MERCHANT_ID = :NEW.MERCHANT_ID),
    SYSDATE);

END;
/