CREATE OR REPLACE TRIGGER sbxtax4."UPD_A_MERCHANTS"
AFTER UPDATE of
 MERCHANT_ID,
ACTIVE,
NAME,
SHORT_NAME,
LEGAL_ENTITY_NAME,
MERCHANT_TYPE,
EXTERNAL_TOKEN,
NOTES,
PARENT_MERCHANT_ID,
XML_ERROR_THRESHOLD,
XML_GROUP_ID,
SPLASH_URL,
IS_CONTENT_PROVIDER,
B2B_FLAG,
FILTER_GROUP_OWNER_ID,
FILTER_GROUP_NAME,
PRODUCT_QUAL_GROUP_OWNER_ID,
PRODUCT_QUAL_GROUP_NAME,
TAX_CODE_QUAL_GROUP_OWNER_ID,
TAX_CODE_QUAL_GROUP_NAME,
SOURCE_SYSTEM_ID,
CUSTOMER_GROUP_ID,
USES_EXEMPT_CERTS,
REGISTRATION_GROUP_ID,
CREATE_AUTO_CERTS,
CREATE_CUSTOMERS,
DAYS_VALID,
DEFAULT_CERT_STATUS,
EXEMPT_TEMP_CERT_TRANS,
US_CONTENT_PROVIDER_ID,
INTL_CONTENT_PROVIDER_ID,
CONTENT_VERSION,
CONTENT_COMMENT,
CONTENT_TYPE,
DEF_INTL_EXEMPT_REASON_ID,
DEF_US_EXEMPT_REASON_ID,
B2B_CREATE_MERCHANT,
B2B_PARENT_MERCHANT_ID,
B2B_USE_PARENT_PREFS,
PRODUCT_CROSS_REF_GROUP_ID,
US_ESTABLISHED_MERCHANT_ID,
INTL_ESTABLISHED_MERCHANT_ID,
US_CUSTOM_DATA_PROVIDER_ID,
INTL_CUSTOM_DATA_PROVIDER_ID,
US_EXCHANGE_RATE_MERCHANT_ID,
INTL_EXCHANGE_RATE_MERCHANT_ID,
ALLOCATION_GROUP_OWNER_ID,
ALLOCATION_GROUP_NAME,
US_PRODUCT_GROUP_ID,
INTL_PRODUCT_GROUP_ID
  ON sbxtax4.TB_MERCHANTS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
      WHEN (
  (
decode(NEW.MERCHANT_ID,OLD.MERCHANT_ID,0,1) +
decode(NEW.ACTIVE,OLD.ACTIVE,0,1) +
decode(NEW.NAME,OLD.NAME,0,1) +
decode(NEW.SHORT_NAME,OLD.SHORT_NAME,0,1) +
decode(NEW.LEGAL_ENTITY_NAME,OLD.LEGAL_ENTITY_NAME,0,1) +
decode(NEW.MERCHANT_TYPE,OLD.MERCHANT_TYPE,0,1) +
decode(NEW.EXTERNAL_TOKEN,OLD.EXTERNAL_TOKEN,0,1) +
decode(NEW.NOTES,OLD.NOTES,0,1) +
decode(NEW.PARENT_MERCHANT_ID,OLD.PARENT_MERCHANT_ID,0,1) +
decode(NEW.XML_ERROR_THRESHOLD,OLD.XML_ERROR_THRESHOLD,0,1) +
decode(NEW.XML_GROUP_ID,OLD.XML_GROUP_ID,0,1) +
decode(NEW.SPLASH_URL,OLD.SPLASH_URL,0,1) +
decode(NEW.IS_CONTENT_PROVIDER,OLD.IS_CONTENT_PROVIDER,0,1) +
decode(NEW.B2B_FLAG,OLD.B2B_FLAG,0,1) +
decode(NEW.FILTER_GROUP_OWNER_ID,OLD.FILTER_GROUP_OWNER_ID,0,1) +
decode(NEW.FILTER_GROUP_NAME,OLD.FILTER_GROUP_NAME,0,1) +
decode(NEW.PRODUCT_QUAL_GROUP_OWNER_ID,OLD.PRODUCT_QUAL_GROUP_OWNER_ID,0,1) +
decode(NEW.PRODUCT_QUAL_GROUP_NAME,OLD.PRODUCT_QUAL_GROUP_NAME,0,1) +
decode(NEW.TAX_CODE_QUAL_GROUP_OWNER_ID,OLD.TAX_CODE_QUAL_GROUP_OWNER_ID,0,1) +
decode(NEW.TAX_CODE_QUAL_GROUP_NAME,OLD.TAX_CODE_QUAL_GROUP_NAME,0,1) +
decode(NEW.SOURCE_SYSTEM_ID,OLD.SOURCE_SYSTEM_ID,0,1) +
decode(NEW.CUSTOMER_GROUP_ID,OLD.CUSTOMER_GROUP_ID,0,1) +
decode(NEW.USES_EXEMPT_CERTS,OLD.USES_EXEMPT_CERTS,0,1) +
decode(NEW.REGISTRATION_GROUP_ID,OLD.REGISTRATION_GROUP_ID,0,1) +
decode(NEW.CREATE_AUTO_CERTS,OLD.CREATE_AUTO_CERTS,0,1) +
decode(NEW.CREATE_CUSTOMERS,OLD.CREATE_CUSTOMERS,0,1) +
decode(NEW.DAYS_VALID,OLD.DAYS_VALID,0,1) +
decode(NEW.DEFAULT_CERT_STATUS,OLD.DEFAULT_CERT_STATUS,0,1) +
decode(NEW.EXEMPT_TEMP_CERT_TRANS,OLD.EXEMPT_TEMP_CERT_TRANS,0,1) +
decode(NEW.US_CONTENT_PROVIDER_ID,OLD.US_CONTENT_PROVIDER_ID,0,1) +
decode(NEW.INTL_CONTENT_PROVIDER_ID,OLD.INTL_CONTENT_PROVIDER_ID,0,1) +
decode(NEW.CONTENT_VERSION,OLD.CONTENT_VERSION,0,1) +
decode(NEW.CONTENT_COMMENT,OLD.CONTENT_COMMENT,0,1) +
decode(NEW.CONTENT_TYPE,OLD.CONTENT_TYPE,0,1) +
decode(NEW.DEF_INTL_EXEMPT_REASON_ID,OLD.DEF_INTL_EXEMPT_REASON_ID,0,1) +
decode(NEW.DEF_US_EXEMPT_REASON_ID,OLD.DEF_US_EXEMPT_REASON_ID,0,1) +
decode(NEW.B2B_CREATE_MERCHANT,OLD.B2B_CREATE_MERCHANT,0,1) +
decode(NEW.B2B_PARENT_MERCHANT_ID,OLD.B2B_PARENT_MERCHANT_ID,0,1) +
decode(NEW.B2B_USE_PARENT_PREFS,OLD.B2B_USE_PARENT_PREFS,0,1) +
decode(NEW.PRODUCT_CROSS_REF_GROUP_ID,OLD.PRODUCT_CROSS_REF_GROUP_ID,0,1) +
decode(NEW.US_ESTABLISHED_MERCHANT_ID,OLD.US_ESTABLISHED_MERCHANT_ID,0,1) +
decode(NEW.INTL_ESTABLISHED_MERCHANT_ID,OLD.INTL_ESTABLISHED_MERCHANT_ID,0,1) +
decode(NEW.US_CUSTOM_DATA_PROVIDER_ID,OLD.US_CUSTOM_DATA_PROVIDER_ID,0,1) +
decode(NEW.INTL_CUSTOM_DATA_PROVIDER_ID,OLD.INTL_CUSTOM_DATA_PROVIDER_ID,0,1) +
decode(NEW.US_EXCHANGE_RATE_MERCHANT_ID,OLD.US_EXCHANGE_RATE_MERCHANT_ID,0,1) +
decode(NEW.INTL_EXCHANGE_RATE_MERCHANT_ID,OLD.INTL_EXCHANGE_RATE_MERCHANT_ID,0,1) +
decode(NEW.ALLOCATION_GROUP_OWNER_ID,OLD.ALLOCATION_GROUP_OWNER_ID,0,1) +
decode(NEW.ALLOCATION_GROUP_NAME,OLD.ALLOCATION_GROUP_NAME,0,1) +
decode(NEW.IS_AUDITING_MESSAGES,OLD.IS_AUDITING_MESSAGES,0,1) +
decode(NEW.AUDIT_MESSAGE_THRESHOLD,OLD.AUDIT_MESSAGE_THRESHOLD,0,1) +
decode(NEW.IS_USING_REPORTING_PERIODS,OLD.IS_USING_REPORTING_PERIODS,0,1) +
decode(NEW.US_PRODUCT_GROUP_ID,OLD.US_PRODUCT_GROUP_ID,0,1) +
decode(NEW.INTL_PRODUCT_GROUP_ID,OLD.INTL_PRODUCT_GROUP_ID,0,1)
  ) > 0

) BEGIN
/* not needed for Content Repository Schema as the merchant change could be done at any time and is not indicative of the version
UPDATE A_AUTHORITIES SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
UPDATE A_AUTHORITY_REQUIREMENTS SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
UPDATE A_CONTRIBUTING_AUTHORITIES SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
UPDATE A_PRODUCT_CATEGORIES SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
UPDATE A_RATE_TIERS SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
UPDATE A_RATES SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
UPDATE A_REFERENCE_LISTS SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
UPDATE A_REFERENCE_VALUES SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
UPDATE A_RULE_QUALIFIERS SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
UPDATE A_RULES SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
UPDATE A_ZONE_AUTHORITIES SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
UPDATE A_ZONE_MATCH_PATTERNS SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
UPDATE A_ZONE_MATCH_CONTEXTS SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
UPDATE A_ZONES SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
UPDATE A_APP_ERRORS SET CHANGE_VERSION = :NEW.CONTENT_VERSION WHERE CHANGE_VERSION IS NULL;
*/

  INSERT INTO A_MERCHANTS (
   MERCHANT_ID,
ACTIVE,
NAME,
SHORT_NAME,
LEGAL_ENTITY_NAME,
MERCHANT_TYPE,
EXTERNAL_TOKEN,
NOTES,
PARENT_MERCHANT_ID,
CREATED_BY,
XML_ERROR_THRESHOLD,
XML_GROUP_ID,
SPLASH_URL,
IS_CONTENT_PROVIDER,
B2B_FLAG,
FILTER_GROUP_OWNER_ID,
FILTER_GROUP_NAME,
PRODUCT_QUAL_GROUP_OWNER_ID,
PRODUCT_QUAL_GROUP_NAME,
TAX_CODE_QUAL_GROUP_OWNER_ID,
TAX_CODE_QUAL_GROUP_NAME,
SOURCE_SYSTEM_ID,
CUSTOMER_GROUP_ID,
USES_EXEMPT_CERTS,
REGISTRATION_GROUP_ID,
CREATE_AUTO_CERTS,
CREATE_CUSTOMERS,
DAYS_VALID,
DEFAULT_CERT_STATUS,
EXEMPT_TEMP_CERT_TRANS,
US_CONTENT_PROVIDER_ID,
INTL_CONTENT_PROVIDER_ID,
CONTENT_VERSION,
CONTENT_COMMENT,
CONTENT_TYPE,
DEF_INTL_EXEMPT_REASON_ID,
DEF_US_EXEMPT_REASON_ID,
B2B_CREATE_MERCHANT,
B2B_PARENT_MERCHANT_ID,
B2B_USE_PARENT_PREFS,
PRODUCT_CROSS_REF_GROUP_ID,
US_ESTABLISHED_MERCHANT_ID,
INTL_ESTABLISHED_MERCHANT_ID,
US_CUSTOM_DATA_PROVIDER_ID,
INTL_CUSTOM_DATA_PROVIDER_ID,
US_EXCHANGE_RATE_MERCHANT_ID,
INTL_EXCHANGE_RATE_MERCHANT_ID,
ALLOCATION_GROUP_OWNER_ID,
ALLOCATION_GROUP_NAME,
US_PRODUCT_GROUP_ID,
INTL_PRODUCT_GROUP_ID,
MERCHANT_ID_O,
ACTIVE_O,
NAME_O,
SHORT_NAME_O,
LEGAL_ENTITY_NAME_O,
MERCHANT_TYPE_O,
EXTERNAL_TOKEN_O,
NOTES_O,
PARENT_MERCHANT_ID_O,
XML_ERROR_THRESHOLD_O,
XML_GROUP_ID_O,
SPLASH_URL_O,
IS_CONTENT_PROVIDER_O,
B2B_FLAG_O,
FILTER_GROUP_OWNER_ID_O,
FILTER_GROUP_NAME_O,
PRODUCT_QUAL_GROUP_OWNER_ID_O,
PRODUCT_QUAL_GROUP_NAME_O,
TAX_CODE_QUAL_GROUP_OWNER_ID_O,
TAX_CODE_QUAL_GROUP_NAME_O,
SOURCE_SYSTEM_ID_O,
CUSTOMER_GROUP_ID_O,
USES_EXEMPT_CERTS_O,
REGISTRATION_GROUP_ID_O,
CREATE_AUTO_CERTS_O,
CREATE_CUSTOMERS_O,
DAYS_VALID_O,
DEFAULT_CERT_STATUS_O,
EXEMPT_TEMP_CERT_TRANS_O,
US_CONTENT_PROVIDER_ID_O,
INTL_CONTENT_PROVIDER_ID_O,
CONTENT_VERSION_O,
CONTENT_COMMENT_O,
CONTENT_TYPE_O,
DEF_INTL_EXEMPT_REASON_ID_O,
DEF_US_EXEMPT_REASON_ID_O,
B2B_CREATE_MERCHANT_O,
B2B_PARENT_MERCHANT_ID_O,
B2B_USE_PARENT_PREFS_O,
PRODUCT_CROSS_REF_GROUP_ID_O,
US_ESTABLISHED_MERCHANT_ID_O,
INTL_ESTABLISHED_MERCHANT_ID_O,
US_CUSTOM_DATA_PROVIDER_ID_O,
INTL_CUSTOM_DATA_PROVIDER_ID_O,
US_EXCHANGE_RATE_MERCHANT_ID_O,
INTL_EXCHGE_RATE_MERCHANT_ID_O,
    CHANGE_DATE
  ) VALUES (
:NEW.MERCHANT_ID,
:NEW.ACTIVE,
:NEW.NAME,
:NEW.SHORT_NAME,
:NEW.LEGAL_ENTITY_NAME,
:NEW.MERCHANT_TYPE,
:NEW.EXTERNAL_TOKEN,
:NEW.NOTES,
:NEW.PARENT_MERCHANT_ID,
:NEW.CREATED_BY,
:NEW.XML_ERROR_THRESHOLD,
:NEW.XML_GROUP_ID,
:NEW.SPLASH_URL,
:NEW.IS_CONTENT_PROVIDER,
:NEW.B2B_FLAG,
:NEW.FILTER_GROUP_OWNER_ID,
:NEW.FILTER_GROUP_NAME,
:NEW.PRODUCT_QUAL_GROUP_OWNER_ID,
:NEW.PRODUCT_QUAL_GROUP_NAME,
:NEW.TAX_CODE_QUAL_GROUP_OWNER_ID,
:NEW.TAX_CODE_QUAL_GROUP_NAME,
:NEW.SOURCE_SYSTEM_ID,
:NEW.CUSTOMER_GROUP_ID,
:NEW.USES_EXEMPT_CERTS,
:NEW.REGISTRATION_GROUP_ID,
:NEW.CREATE_AUTO_CERTS,
:NEW.CREATE_CUSTOMERS,
:NEW.DAYS_VALID,
:NEW.DEFAULT_CERT_STATUS,
:NEW.EXEMPT_TEMP_CERT_TRANS,
:NEW.US_CONTENT_PROVIDER_ID,
:NEW.INTL_CONTENT_PROVIDER_ID,
:NEW.CONTENT_VERSION,
:NEW.CONTENT_COMMENT,
:NEW.CONTENT_TYPE,
:NEW.DEF_INTL_EXEMPT_REASON_ID,
:NEW.DEF_US_EXEMPT_REASON_ID,
:NEW.B2B_CREATE_MERCHANT,
:NEW.B2B_PARENT_MERCHANT_ID,
:NEW.B2B_USE_PARENT_PREFS,
:NEW.PRODUCT_CROSS_REF_GROUP_ID,
:NEW.US_ESTABLISHED_MERCHANT_ID,
:NEW.INTL_ESTABLISHED_MERCHANT_ID,
:NEW.US_CUSTOM_DATA_PROVIDER_ID,
:NEW.INTL_CUSTOM_DATA_PROVIDER_ID,
:NEW.US_EXCHANGE_RATE_MERCHANT_ID,
:NEW.INTL_EXCHANGE_RATE_MERCHANT_ID,
:NEW.ALLOCATION_GROUP_OWNER_ID,
:NEW.ALLOCATION_GROUP_NAME,
:NEW.US_PRODUCT_GROUP_ID,
:NEW.INTL_PRODUCT_GROUP_ID,
:OLD.MERCHANT_ID,
:OLD.ACTIVE,
:OLD.NAME,
:OLD.SHORT_NAME,
:OLD.LEGAL_ENTITY_NAME,
:OLD.MERCHANT_TYPE,
:OLD.EXTERNAL_TOKEN,
:OLD.NOTES,
:OLD.PARENT_MERCHANT_ID,
:OLD.XML_ERROR_THRESHOLD,
:OLD.XML_GROUP_ID,
:OLD.SPLASH_URL,
:OLD.IS_CONTENT_PROVIDER,
:OLD.B2B_FLAG,
:OLD.FILTER_GROUP_OWNER_ID,
:OLD.FILTER_GROUP_NAME,
:OLD.PRODUCT_QUAL_GROUP_OWNER_ID,
:OLD.PRODUCT_QUAL_GROUP_NAME,
:OLD.TAX_CODE_QUAL_GROUP_OWNER_ID,
:OLD.TAX_CODE_QUAL_GROUP_NAME,
:OLD.SOURCE_SYSTEM_ID,
:OLD.CUSTOMER_GROUP_ID,
:OLD.USES_EXEMPT_CERTS,
:OLD.REGISTRATION_GROUP_ID,
:OLD.CREATE_AUTO_CERTS,
:OLD.CREATE_CUSTOMERS,
:OLD.DAYS_VALID,
:OLD.DEFAULT_CERT_STATUS,
:OLD.EXEMPT_TEMP_CERT_TRANS,
:OLD.US_CONTENT_PROVIDER_ID,
:OLD.INTL_CONTENT_PROVIDER_ID,
:OLD.CONTENT_VERSION,
:OLD.CONTENT_COMMENT,
:OLD.CONTENT_TYPE,
:OLD.DEF_INTL_EXEMPT_REASON_ID,
:OLD.DEF_US_EXEMPT_REASON_ID,
:OLD.B2B_CREATE_MERCHANT,
:OLD.B2B_PARENT_MERCHANT_ID,
:OLD.B2B_USE_PARENT_PREFS,
:OLD.PRODUCT_CROSS_REF_GROUP_ID,
:OLD.US_ESTABLISHED_MERCHANT_ID,
:OLD.INTL_ESTABLISHED_MERCHANT_ID,
:OLD.US_CUSTOM_DATA_PROVIDER_ID,
:OLD.INTL_CUSTOM_DATA_PROVIDER_ID,
:OLD.US_EXCHANGE_RATE_MERCHANT_ID,
:OLD.INTL_EXCHANGE_RATE_MERCHANT_ID,
    SYSDATE);
END;
/