CREATE OR REPLACE TRIGGER sbxtax4."UPD_A_APP_ERRORS"
AFTER UPDATE OF
ERROR_ID,
ERROR_NUM,
ERROR_SEVERITY,
TITLE,
DESCRIPTION,
CAUSE,
ACTION,
CATEGORY,
MERCHANT_ID,
AUTHORITY_ID
ON sbxtax4.TB_APP_ERRORS
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
      WHEN (
(
decode(NEW.ERROR_ID,OLD.ERROR_ID,0,1) +
decode(NEW.ERROR_NUM,OLD.ERROR_NUM,0,1) +
decode(NEW.ERROR_SEVERITY,OLD.ERROR_SEVERITY,0,1) +
decode(NEW.TITLE,OLD.TITLE,0,1) +
decode(NEW.DESCRIPTION,OLD.DESCRIPTION,0,1) +
decode(NEW.CAUSE,OLD.CAUSE,0,1) +
decode(NEW.ACTION,OLD.ACTION,0,1) +
decode(NEW.CATEGORY,OLD.CATEGORY,0,1) +
decode(NEW.MERCHANT_ID,OLD.MERCHANT_ID,0,1) +
decode(NEW.AUTHORITY_ID,OLD.AUTHORITY_ID,0,1)
) > 0
) BEGIN
  INSERT INTO A_APP_ERRORS (
ERROR_ID,
ERROR_NUM,
ERROR_SEVERITY,
TITLE,
DESCRIPTION,
CAUSE,
ACTION,
CREATED_BY,
CREATION_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
--SYNCHRONIZATION_TIMESTAMP,
CATEGORY,
MERCHANT_ID,
AUTHORITY_ID,
ERROR_ID_O,
ERROR_NUM_O,
ERROR_SEVERITY_O,
TITLE_O,
DESCRIPTION_O,
CAUSE_O,
ACTION_O,
CREATED_BY_O,
CREATION_DATE_O,
LAST_UPDATED_BY_O,
LAST_UPDATE_DATE_O,
--SYNCHRONIZATION_TIMESTAMP_O,
CATEGORY_O,
MERCHANT_ID_O,
AUTHORITY_ID_O,
CHANGE_TYPE,
--CHANGE_VERSION,
CHANGE_DATE
  ) VALUES (
:NEW.ERROR_ID,
:NEW.ERROR_NUM,
:NEW.ERROR_SEVERITY,
:NEW.TITLE,
:NEW.DESCRIPTION,
:NEW.CAUSE,
:NEW.ACTION,
:NEW.CREATED_BY,
:NEW.CREATION_DATE,
:NEW.LAST_UPDATED_BY,
:NEW.LAST_UPDATE_DATE,
--:NEW.SYNCHRONIZATION_TIMESTAMP,
:NEW.CATEGORY,
:NEW.MERCHANT_ID,
:NEW.AUTHORITY_ID,
:OLD.ERROR_ID,
:OLD.ERROR_NUM,
:OLD.ERROR_SEVERITY,
:OLD.TITLE,
:OLD.DESCRIPTION,
:OLD.CAUSE,
:OLD.ACTION,
:OLD.CREATED_BY,
:OLD.CREATION_DATE,
:OLD.LAST_UPDATED_BY,
:OLD.LAST_UPDATE_DATE,
--:OLD.SYNCHRONIZATION_TIMESTAMP,
:OLD.CATEGORY,
:OLD.MERCHANT_ID,
:OLD.AUTHORITY_ID,
    'UPDATED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS WHERE MERCHANT_ID = :NEW.MERCHANT_ID),
    SYSDATE);
END;
/