--
-- Script generated by Source Control for Oracle 5.2.5.2062 on 02/04/2019 19:46:49
--
SET DEFINE OFF

CREATE TABLE ab134370.apptypealso3 (
  apptypealso3id NUMBER(10) NOT NULL,
  apptypealso3 NVARCHAR2(50) NOT NULL,
  CONSTRAINT pk_apptypealso3 PRIMARY KEY (apptypealso3)
);

