--
-- Script generated by Source Control for Oracle 5.2.5.2062 on 23/04/2019 16:55:43
--
SET DEFINE OFF

CREATE TABLE ab134370.apptype (
  apptypeid NUMBER(10) NOT NULL,
  apptype NVARCHAR2(50) NOT NULL,
  CONSTRAINT pk_apptype_also4 PRIMARY KEY (apptype)
);

