--
-- Script generated by Source Control for Oracle 5.2.5.2062 on 02/04/2019 19:07:24
--
SET DEFINE OFF

CREATE TABLE ab134370.apptype (
  apptypeid NUMBER(10) NOT NULL,
  apptype NVARCHAR2(50) NOT NULL,
  CONSTRAINT pk_apptype PRIMARY KEY (apptype)
);

GRANT INHERIT PRIVILEGES ON USER ab134370 TO PUBLIC;

