--
-- Script generated by Source Control for Oracle 5.2.5.2062 on 02/04/2019 19:17:36
--
SET DEFINE OFF

CREATE TABLE ab134370.apptypealso (
  apptypealsoid NUMBER(10) NOT NULL,
  apptypealso NVARCHAR2(50) NOT NULL,
  CONSTRAINT pk_apptypealso PRIMARY KEY (apptypealso)
);

