--
-- Script generated by Source Control for Oracle 5.2.5.2062 on 02/04/2019 19:27:31
--
SET DEFINE OFF

CREATE OR REPLACE FORCE VIEW ab134370.v_apptype (app_type_id,app_type,created_by,date_created,modified_by,date_modified) AS
SELECT "APP_TYPE_ID","APP_TYPE","CREATED_BY","DATE_CREATED","MODIFIED_BY","DATE_MODIFIED" FROM APP_TYPE;

