--
-- Script generated by Source Control for Oracle 5.2.5.2062 on 02/04/2019 19:39:36
--
SET DEFINE OFF

CREATE TABLE ab134370.apptypealso2 (
  apptypealso2id NUMBER(10) NOT NULL,
  apptypealso2 NVARCHAR2(50) NOT NULL,
  CONSTRAINT pk_apptypealso2 PRIMARY KEY (apptypealso2)
);

