CREATE TABLE content_repo.commodity_tree_build_log (
  process_id NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY,
  job_start DATE,
  PRIMARY KEY (process_id) USING INDEX 
    TABLESPACE content_repo
) 
TABLESPACE content_repo;