CREATE TABLE content_repo.gis_zone_authorities_tmp (
  merchant_id NUMBER,
  zone_1_id NUMBER,
  zone_1_name VARCHAR2(50 CHAR),
  zone_1_level_id VARCHAR2(2 CHAR),
  zone_2_id NUMBER,
  zone_2_name VARCHAR2(50 CHAR),
  zone_2_level_id VARCHAR2(2 CHAR),
  zone_3_id NUMBER,
  zone_3_name VARCHAR2(50 CHAR),
  zone_3_level_id VARCHAR2(2 CHAR),
  zone_4_id NUMBER,
  zone_4_name VARCHAR2(50 CHAR),
  zone_4_level_id VARCHAR2(2 CHAR),
  zone_4_parent_id NUMBER,
  zone_5_id NUMBER,
  zone_5_name VARCHAR2(50 CHAR),
  zone_5_level_id VARCHAR2(2 CHAR),
  zone_5_parent_id NUMBER,
  zone_6_id NUMBER,
  zone_6_name VARCHAR2(50 CHAR),
  zone_6_level_id VARCHAR2(2 CHAR),
  zone_6_parent_id NUMBER,
  zone_7_id NUMBER,
  zone_7_name VARCHAR2(50 CHAR),
  zone_7_level_id VARCHAR2(2 CHAR),
  zone_7_parent_id NUMBER,
  tax_parent_zone VARCHAR2(50 CHAR),
  code_2char VARCHAR2(2 CHAR),
  code_fips VARCHAR2(30 CHAR),
  reverse_flag VARCHAR2(1 CHAR),
  terminator_flag VARCHAR2(1 CHAR),
  default_flag VARCHAR2(1 CHAR),
  range_min NUMBER(10),
  range_max NUMBER(10),
  authority_name VARCHAR2(100 CHAR),
  stj_flag NUMBER(1),
  geo_area VARCHAR2(100 CHAR),
  processed NUMBER
) 
TABLESPACE content_repo;