CREATE TABLE content_repo.gis_indata_areas_sup_temp (
  zip VARCHAR2(5 CHAR),
  zip4 VARCHAR2(4 CHAR),
  zip9 VARCHAR2(12 CHAR),
  "MATCH" VARCHAR2(15 CHAR),
  match_id NUMBER(1),
  biti_id VARCHAR2(20 CHAR),
  "STATE" VARCHAR2(2 CHAR),
  state_name VARCHAR2(50 CHAR),
  state_fips VARCHAR2(2 CHAR),
  county_fips VARCHAR2(4 CHAR),
  county_name VARCHAR2(64 CHAR),
  city_fips VARCHAR2(8 CHAR),
  city_name VARCHAR2(64 CHAR),
  stj1_id VARCHAR2(12 CHAR),
  stj1_name VARCHAR2(100 CHAR),
  stj2_id VARCHAR2(12 CHAR),
  stj2_name VARCHAR2(100 CHAR),
  stj3_id VARCHAR2(12 CHAR),
  stj3_name VARCHAR2(100 CHAR),
  stj4_id VARCHAR2(12 CHAR),
  stj4_name VARCHAR2(100 CHAR),
  stj5_id VARCHAR2(12 CHAR),
  stj5_name VARCHAR2(100 CHAR),
  stj6_id VARCHAR2(12 CHAR),
  stj6_name VARCHAR2(100 CHAR),
  stj7_id VARCHAR2(12 CHAR),
  stj7_name VARCHAR2(100 CHAR),
  stj8_id VARCHAR2(12 CHAR),
  stj8_name VARCHAR2(100 CHAR),
  stj9_id VARCHAR2(12 CHAR),
  stj9_name VARCHAR2(100 CHAR),
  area_id VARCHAR2(60 CHAR),
  taxid VARCHAR2(20 CHAR),
  unique_area VARCHAR2(500 CHAR),
  multiple_counties NUMBER DEFAULT 0,
  multiple_cities NUMBER DEFAULT 0,
  county_rank NUMBER,
  city_rank NUMBER,
  default_city CHAR(1 CHAR),
  default_zip CHAR(1 CHAR),
  default_zip4 CHAR(1 CHAR),
  city_startdate DATE,
  city_enddate DATE,
  state_geo_area_key VARCHAR2(100 CHAR),
  county_geo_area_key VARCHAR2(100 CHAR),
  city_geo_area_key VARCHAR2(100 CHAR),
  stj1_geo_area_key VARCHAR2(100 CHAR),
  stj2_geo_area_key VARCHAR2(100 CHAR),
  stj3_geo_area_key VARCHAR2(100 CHAR),
  stj4_geo_area_key VARCHAR2(100 CHAR),
  stj5_geo_area_key VARCHAR2(100 CHAR),
  stj6_geo_area_key VARCHAR2(100 CHAR),
  stj7_geo_area_key VARCHAR2(100 CHAR),
  stj8_geo_area_key VARCHAR2(100 CHAR),
  stj9_geo_area_key VARCHAR2(100 CHAR),
  stj_name VARCHAR2(500 CHAR),
  stj1_startdate DATE,
  stj2_startdate DATE,
  stj3_startdate DATE,
  stj4_startdate DATE,
  stj5_startdate DATE,
  stj6_startdate DATE,
  stj7_startdate DATE,
  stj8_startdate DATE,
  stj9_startdate DATE,
  stj1_enddate DATE,
  stj2_enddate DATE,
  stj3_enddate DATE,
  stj4_enddate DATE,
  stj5_enddate DATE,
  stj6_enddate DATE,
  stj7_enddate DATE,
  stj8_enddate DATE,
  stj9_enddate DATE
) 
TABLESPACE content_repo;