CREATE TABLE content_repo.jurismsg_severity_lookups (
  severity_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  severity_code VARCHAR2(100 BYTE) NOT NULL,
  severity_description VARCHAR2(200 BYTE) NOT NULL,
  entered_by NUMBER NOT NULL,
  entered_date TIMESTAMP NOT NULL,
  "ACTIVE" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL,
  status NUMBER DEFAULT 0 NOT NULL,
  status_modified_date TIMESTAMP NOT NULL,
  CONSTRAINT jurismsg_severity_pk PRIMARY KEY (severity_id) USING INDEX 
    TABLESPACE content_repo
) 
TABLESPACE content_repo;