CREATE TABLE content_repo.juris_tax_applicabilities (
  "ID" NUMBER NOT NULL,
  reference_code VARCHAR2(100 CHAR) NOT NULL,
  calculation_method_id NUMBER NOT NULL,
  basis_percent NUMBER DEFAULT 100,
  recoverable_percent NUMBER DEFAULT 100,
  start_date DATE,
  end_date DATE,
  entered_by NUMBER NOT NULL,
  entered_date TIMESTAMP WITH TIME ZONE NOT NULL,
  status NUMBER DEFAULT 0 NOT NULL,
  status_modified_date TIMESTAMP WITH TIME ZONE NOT NULL,
  rid NUMBER NOT NULL,
  nkid NUMBER NOT NULL,
  next_rid NUMBER,
  jurisdiction_id NUMBER NOT NULL,
  jurisdiction_nkid NUMBER NOT NULL,
  all_taxes_apply NUMBER(1) DEFAULT 0 NOT NULL,
  recoverable_amount NUMBER,
  applicability_type_id NUMBER NOT NULL,
  unit_of_measure VARCHAR2(16 CHAR),
  ref_rule_order NUMBER,
  default_taxability VARCHAR2(1 CHAR),
  product_tree_id NUMBER,
  commodity_id NUMBER,
  tax_type VARCHAR2(4 CHAR),
  is_local VARCHAR2(1 CHAR),
  "EXEMPT" VARCHAR2(1 CHAR),
  no_tax VARCHAR2(1 CHAR),
  commodity_nkid NUMBER,
  charge_type_id NUMBER,
  CONSTRAINT juris_tax_applicabilities_pk PRIMARY KEY ("ID") USING INDEX 
    TABLESPACE content_repo,
  CONSTRAINT juris_tax_applicabilities_f1 FOREIGN KEY (jurisdiction_id) REFERENCES content_repo.jurisdictions ("ID"),
  CONSTRAINT juris_tax_applicabilities_f2 FOREIGN KEY (rid,nkid) REFERENCES content_repo.juris_tax_app_revisions ("ID",nkid),
  CONSTRAINT juris_tax_applicabilities_f3 FOREIGN KEY (calculation_method_id) REFERENCES content_repo.calculation_methods ("ID"),
  CONSTRAINT juris_tax_applicabilities_f4 FOREIGN KEY (charge_type_id) REFERENCES content_repo.charge_types ("ID"),
  CONSTRAINT juris_tax_applicabilities_f5 FOREIGN KEY (product_tree_id) REFERENCES content_repo.product_trees ("ID"),
  CONSTRAINT juris_tax_applicabilities_f6 FOREIGN KEY (commodity_id) REFERENCES content_repo.commodities ("ID")
) 
TABLESPACE content_repo;