CREATE TABLE content_repo.kpmg_rates (
  ratekeyid NUMBER(22),
  taxboundaryid NUMBER(22),
  taxboundarystate VARCHAR2(40 BYTE),
  taxboundarylevel VARCHAR2(20 BYTE),
  taxboundaryname VARCHAR2(100 BYTE),
  rateauthlevel VARCHAR2(20 BYTE),
  taxtypeid NUMBER(22),
  taxtypegroupcode NUMBER(22),
  taxtypeclasscode VARCHAR2(10 BYTE),
  transactiontype VARCHAR2(50 BYTE),
  rateid NUMBER(22),
  taxratedescription VARCHAR2(200 BYTE),
  taxtypegroupdesc VARCHAR2(50 BYTE),
  taxtypeclassdesc VARCHAR2(50 BYTE),
  taxratevalue VARCHAR2(30 BYTE),
  taxratetype VARCHAR2(30 BYTE),
  taxratebasis VARCHAR2(10 BYTE),
  taxratecalctype VARCHAR2(40 BYTE),
  ratethresholdbasis VARCHAR2(10 BYTE),
  rateslidingscaletype VARCHAR2(20 BYTE),
  tieredrateisdefault VARCHAR2(30 BYTE),
  tieredratevalue VARCHAR2(30 BYTE),
  tieredrateupperlimit VARCHAR2(30 BYTE),
  start_date DATE,
  end_date DATE,
  import_tax VARCHAR2(1 BYTE),
  cm_id VARCHAR2(10 BYTE),
  tax_description_id NUMBER,
  official_name VARCHAR2(150 BYTE),
  "IMPORT" VARCHAR2(2 BYTE),
  reference_code VARCHAR2(20 BYTE),
  tax_admin VARCHAR2(100 BYTE),
  tax_description VARCHAR2(300 BYTE),
  transaction_type VARCHAR2(300 BYTE),
  processed VARCHAR2(5 BYTE),
  taxdescname VARCHAR2(100 BYTE),
  taxdescid NUMBER,
  kpmg_specific VARCHAR2(10 BYTE)
) 
TABLESPACE content_repo;