CREATE TABLE content_repo.tdr_etl_process (
  processid NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 10),
  etl_params CLOB CONSTRAINT etl_params_chk CHECK (etl_params IS JSON) DISABLE NOVALIDATE,
  entered_date DATE DEFAULT sysdate,
  PRIMARY KEY (processid) USING INDEX 
    TABLESPACE content_repo
) 
TABLESPACE content_repo
LOB (etl_params) STORE AS SECUREFILE (
  ENABLE STORAGE IN ROW);