CREATE TABLE content_repo.tdr_nls_convert (
  "ID" NUMBER GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 10),
  incharacter VARCHAR2(4 BYTE),
  convertto VARCHAR2(2 BYTE),
  PRIMARY KEY ("ID") USING INDEX 
    TABLESPACE content_repo
) 
TABLESPACE content_repo;
COMMENT ON TABLE content_repo.tdr_nls_convert IS 'Translate characters';