CREATE TABLE content_repo.tdr_publish_log (
  "ID" NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY,
  entity_id NUMBER,
  entered_by NUMBER,
  publish_date DATE,
  rid NUMBER,
  nkid NUMBER,
  PRIMARY KEY ("ID") USING INDEX 
    TABLESPACE content_repo
) 
TABLESPACE content_repo;