CREATE TABLE content_repo.vgeo_unique_areas2 (
  zip VARCHAR2(5 CHAR),
  zip9 VARCHAR2(21 CHAR),
  state_code VARCHAR2(2 CHAR) NOT NULL,
  state_name VARCHAR2(64 CHAR) NOT NULL,
  county_name VARCHAR2(64 CHAR),
  city_name VARCHAR2(122 CHAR),
  unique_area VARCHAR2(32767 CHAR),
  area_id VARCHAR2(60 CHAR)
) TABLESPACE content_repo
LOB (unique_area) STORE AS SECUREFILE (
  ENABLE STORAGE IN ROW)
PARTITION BY LIST (state_code)
(PARTITION mv_ua_al VALUES ('AL')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ak VALUES ('AK')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ar VALUES ('AR')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_az VALUES ('AZ')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_aa VALUES ('AA')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ae VALUES ('AE')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ap VALUES ('AP')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_as VALUES ('AS')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ca VALUES ('CA')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_co VALUES ('CO')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ct VALUES ('CT')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_de VALUES ('DE')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_dc VALUES ('DC')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_fl VALUES ('FL')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_fm VALUES ('FM')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ga VALUES ('GA')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_gu VALUES ('GU')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_hi VALUES ('HI')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_id VALUES ('ID')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_il VALUES ('IL')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_in VALUES ('IN')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ia VALUES ('IA')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ks VALUES ('KS')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ky VALUES ('KY')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_la VALUES ('LA')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_me VALUES ('ME')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_md VALUES ('MD')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ma VALUES ('MA')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_mi VALUES ('MI')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_mn VALUES ('MN')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ms VALUES ('MS')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_mo VALUES ('MO')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_mt VALUES ('MT')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_mh VALUES ('MH')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_mp VALUES ('MP')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ne VALUES ('NE')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_nv VALUES ('NV')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_nh VALUES ('NH')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_nj VALUES ('NJ')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_nm VALUES ('NM')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ny VALUES ('NY')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_nc VALUES ('NC')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_nd VALUES ('ND')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_oh VALUES ('OH')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ok VALUES ('OK')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_or VALUES ('OR')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_pa VALUES ('PA')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_pr VALUES ('PR')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_pw VALUES ('PW')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ri VALUES ('RI')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_sc VALUES ('SC')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_sd VALUES ('SD')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_tn VALUES ('TN')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_tx VALUES ('TX')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_ut VALUES ('UT')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_va VALUES ('VA')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_vt VALUES ('VT')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_vi VALUES ('VI')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_wa VALUES ('WA')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_wv VALUES ('WV')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_wi VALUES ('WI')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_wy VALUES ('WY')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_us VALUES ('US')
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW),
PARTITION mv_ua_x0 VALUES (DEFAULT)
  INDEXING ON
  TABLESPACE content_repo
  LOB (unique_area) STORE AS SECUREFILE (
    ENABLE STORAGE IN ROW));