CREATE INDEX content_repo.gis_zone_auth_budetail_tmp_n1 ON content_repo.gis_zone_auth_budetail_tmp(zone_3_name,zone_4_name,zone_5_name,zone_6_name,zone_7_name,authority_name)

TABLESPACE content_repo;