CREATE OR REPLACE TYPE content_repo."IMPL_EXPL_XVIEW"                                          IS OBJECT (
IMPLICIT number,
IMPLEXPL_AUTH_LEVEL number,
IMPL_CM_ORDER number,
ID                             NUMBER                ,
REFERENCE_CODE                 VARCHAR2(100 CHAR)    ,
CALCULATION_METHOD_ID          NUMBER                ,
BASIS_PERCENT                  NUMBER,
RECOVERABLE_PERCENT            NUMBER,
RECOVERABLE_AMOUNT             NUMBER,
START_DATE                     DATE,
END_DATE                       DATE,
ENTERED_BY                     NUMBER,
ENTERED_DATE                   DATE,
STATUS                         NUMBER,
STATUS_MODIFIED_DATE           DATE,
RID                            NUMBER,
NKID                           NUMBER,
NEXT_RID                       NUMBER(22,0),
JURISDICTION_ID                NUMBER       ,
JURISDICTION_NKID              NUMBER       ,
JURISDICTION_RID               NUMBER,
JURISDICTION_OFFICIAL_NAME     VARCHAR2(250 CHAR),
ALL_TAXES_APPLY                NUMBER(1,0)        ,
APPLICABILITY_TYPE_ID          NUMBER             ,
CHARGE_TYPE_ID                 NUMBER,
UNIT_OF_MEASURE                VARCHAR2(16 CHAR),
REF_RULE_ORDER                 NUMBER,
DEFAULT_TAXABILITY             NUMBER,
PRODUCT_TREE_ID                NUMBER,
COMMODITY_ID                   NUMBER,
COMMODITY_NKID                 NUMBER,
COMMODITY_RID                  NUMBER,
COMMODITY_NAME                 VARCHAR2(500 BYTE),
COMMODITY_CODE                 VARCHAR2(100 CHAR),
H_CODE                         VARCHAR2(128 CHAR),
CONDITIONS                     CHAR(1 BYTE),
TAX_TYPE                       VARCHAR2(4 CHAR),
TAX_APPLICABILITIES            VARCHAR2(4000 CHAR),
VERIFICATION                   VARCHAR2(7 BYTE),
CHANGE_COUNT                   NUMBER,
COMMODITY_TREE_ID              NUMBER,
IS_LOCAL                       NUMBER,
LEGAL_STATEMENT                VARCHAR2(500 CHAR),
CANBEDELETED                   NUMBER,
MAXSTATUS                      NUMBER,
TAG_COLLECTION                 VARCHAR2(4000 CHAR),
CONDITION_COLLECTION           VARCHAR2(4000 CHAR),
APPLICABLE_TAX_COLLECTION      VARCHAR2(4000 CHAR),
OVERRIDE_ORDER                 NUMBER,               -- crapp-2754
VERIFYLIST                     VARCHAR2(4000 CHAR),  -- crapp-2801
SOURCE_H_CODE                  VARCHAR2(128 CHAR)    -- crapp-2908
)
/