CREATE OR REPLACE TRIGGER content_repo."DEL_JURISDICTION_ATTRIBUTES"
 AFTER
 DELETE
 ON content_repo.JURISDICTION_ATTRIBUTES
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW
BEGIN
    DELETE FROM juris_chg_logs
     WHERE rid = :old.rid and primary_key = :old.id
       AND table_name = 'JURISDICTION_ATTRIBUTES';
END;
/