CREATE OR REPLACE TRIGGER content_repo."DEL_TRANSACTION_TAXABILITIES" 
 AFTER
  DELETE
 ON content_repo.TRANSACTION_TAXABILITIES
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
    DELETE FROM juris_tax_app_chg_logs WHERE rid = :old.rid and primary_key = :old.id AND table_name = 'TRANSACTION_TAXABILITIES';
END;
/