create or replace TRIGGER CONTENT_REPO.INS_JURIS_MSG_SEVERITY_LOOKUPS
 BEFORE
  INSERT
 ON JURIS_MSG_SEVERITY_LOOKUPS  
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN

--:new.name_id := pk_jurisoption_name_lookups.nextval;  -- this value is generated by using "generated by " keyword in lookup table
:new.entered_date := SYSTIMESTAMP;
:new.status_modified_date := SYSTIMESTAMP;
END;