CREATE OR REPLACE TRIGGER content_repo."INS_JURIS_TAX_DESC_NKIDS" 
 BEFORE
  INSERT
 ON content_repo.JURIS_TAX_DESCRIPTIONS
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
DECLARE
    l_nkid number;
BEGIN
select nkid
into :new.JURISDICTION_NKID
from jurisdictions
where id = :new.JURISDICTION_ID;

END;
/