create or replace TRIGGER CONTENT_REPO.UPD_JURIS_MSG_SEVERITY_LOOKUPS
 BEFORE
  UPDATE
 ON JURIS_MSG_SEVERITY_LOOKUPS  
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
BEGIN
IF (:old.status = :new.status) THEN
:new.entered_date := SYSTIMESTAMP;
ELSE :new.status_modified_date := SYSTIMESTAMP;
END IF;
END;