CREATE TABLE crapp_admin.logs (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(250 CHAR),
  target VARCHAR2(250 CHAR),
  "PRIORITY" NUMBER(1),
  entered_date TIMESTAMP,
  code VARCHAR2(16 CHAR),
  "TRACE" VARCHAR2(4000 CHAR),
  route VARCHAR2(256 CHAR),
  server_name VARCHAR2(64 CHAR),
  server_ip VARCHAR2(64 CHAR),
  user_ip VARCHAR2(64 CHAR),
  user_os VARCHAR2(128 CHAR),
  user_browser VARCHAR2(256 CHAR),
  message CLOB,
  errno VARCHAR2(256 CHAR),
  line VARCHAR2(6 CHAR),
  "CONTEXT" CLOB,
  user_id VARCHAR2(16 CHAR),
  "DOCUMENT" VARCHAR2(1000 CHAR),
  CONSTRAINT crapp_logs_pk PRIMARY KEY ("ID") USING INDEX 
    TABLESPACE crapp_admin
) 
TABLESPACE crapp_admin
LOB ("CONTEXT") STORE AS SECUREFILE (
  ENABLE STORAGE IN ROW)
LOB (message) STORE AS SECUREFILE (
  ENABLE STORAGE IN ROW)
LOB ("TRACE") STORE AS SECUREFILE (
  ENABLE STORAGE IN ROW);