CREATE TABLE crapp_admin.user_defaults (
  "ID" NUMBER NOT NULL,
  entered_by NUMBER NOT NULL,
  entered_date TIMESTAMP NOT NULL,
  status NUMBER DEFAULT 0 NOT NULL,
  status_modified_date TIMESTAMP NOT NULL,
  tag_search VARCHAR2(1000 CHAR),
  user_id NUMBER NOT NULL,
  users_search VARCHAR2(1000 CHAR),
  contact_reasons VARCHAR2(255 CHAR),
  enable_tags_side NUMBER(1) DEFAULT 1,
  enable_recently_visited_side NUMBER(1) DEFAULT 1,
  enable_unused_entities NUMBER(1) DEFAULT 1,
  enable_links_in_new_tab NUMBER(1) DEFAULT 0,
  enable_contacts_side NUMBER(1) DEFAULT 1,
  enable_quick_search_side NUMBER(1) DEFAULT 1,
  default_language VARCHAR2(8 CHAR),
  enable_end_date_auto_generate NUMBER(1) DEFAULT 1,
  enable_dock_left_sidebar NUMBER(1) DEFAULT 0,
  enable_dock_right_sidebar NUMBER(1) DEFAULT 0,
  default_data_table_length NUMBER(4) DEFAULT 10,
  enable_add_to_calendar NUMBER(1) DEFAULT 1,
  jira_auth_token VARCHAR2(1000 CHAR),
  default_taxability_input_recov NUMBER(3),
  default_publication_tags VARCHAR2(1000 CHAR),
  enable_gis_etl_notifications NUMBER(1) DEFAULT 1,
  default_taxability_calc_method NUMBER(3),
  auto_generate_taxability NUMBER(1) DEFAULT 1,
  default_date_behavior NUMBER(1) DEFAULT 1,
  default_effective_date DATE,
  CONSTRAINT crapp_user_defulats_pk PRIMARY KEY ("ID") USING INDEX 
    TABLESPACE crapp_admin
) 
TABLESPACE crapp_admin;