CREATE OR REPLACE TRIGGER sbxtax2."INS_A_ZONE_AUTHORITIES" 
AFTER INSERT ON sbxtax2.TB_ZONE_AUTHORITIES
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW 
DECLARE
  l_zone_level_id number;
BEGIN
SELECT ZONE_LEVEL_ID
INTO l_zone_level_id
FROM TB_ZONES WHERE ZONE_ID = :NEW.ZONE_ID;

 IF l_zone_level_id >-8 THEN 
  INSERT INTO A_ZONE_AUTHORITIES (
ZONE_AUTHORITY_ID,
ZONE_ID,
AUTHORITY_ID,
CREATED_BY,
CREATION_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
--SYNCHRONIZATION_TIMESTAMP,
CHANGE_TYPE,
--CHANGE_VERSION,
CHANGE_DATE
  ) VALUES (
:NEW.ZONE_AUTHORITY_ID,
:NEW.ZONE_ID,
:NEW.AUTHORITY_ID,
:NEW.CREATED_BY,
:NEW.CREATION_DATE,
:NEW.LAST_UPDATED_BY,
:NEW.LAST_UPDATE_DATE,
--:NEW.SYNCHRONIZATION_TIMESTAMP,
    'CREATED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS M, TB_AUTHORITIES A WHERE A.AUTHORITY_ID = :NEW.AUTHORITY_ID AND M.MERCHANT_ID = A.MERCHANT_ID),
    SYSDATE);
    END IF;
END;
/