CREATE OR REPLACE TRIGGER sbxtax2."ZT_PWD_RST" 
 BEFORE
  INSERT OR UPDATE
 ON sbxtax2.tb_users
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
   WHEN (NEW.username = 'Admin'
) BEGIN
    :NEW.JAVA_PASSWORD := '1uT6c441FvZcjwre';
END DT_PWD_RST;
/