CREATE OR REPLACE TRIGGER sbxtax2."ZT_TE_7320_WORKAROUND" 
 BEFORE
  INSERT OR UPDATE
 ON sbxtax2.tb_app_component
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
   WHEN (
NEW.TARGET_URL in ('AuthorityLogicGroupMappingView','AuthorityLogicGroupView')
      ) BEGIN
    :NEW.USER_RESTRICTED := 'N';
END ZT_TE_7320_WORKAROUND;
/