CREATE OR REPLACE PROCEDURE crapp_admin."CREATE_MANAGER_USER" (userName in varchar2 ) is
v_user_uid NUMBER;
v_mgr_uid NUMBER;
BEGIN
INSERT INTO crapp_admin.users
(USERNAME,ENTERED_BY,ENTERED_DATE,STATUS,STATUS_MODIFIED_DATE,PASSWORD,EMAIL,FIRSTNAME,LASTNAME,COSTCENTER,COMPANY,MARKETGROUP,MGOVERRIDE,
PAYGROUP,THOMSLOCATION,RESET_TOKEN,RESET_EXPIRE)
VALUES('555555','3',SYSDATE,'1',SYSDATE,'5d9c68c6c50ed3d02a2fcf54f63993b6','steven.martindale@tr.com','Test','Admin','','','','','','','','');
SELECT id INTO v_mgr_uid FROM crapp_admin.users WHERE username = '555555';
INSERT INTO crapp_admin.user_roles
(USER_ID,ROLE_ID,ACTIVE_DATE,EXPIRE_DATE,ENTERED_BY,ENTERED_DATE)
VALUES(v_mgr_uid,'manager','','','','');
END;
/