CREATE OR REPLACE TRIGGER sbxtax3."UPD_A_RULE_QUALIFIERS" 
AFTER UPDATE OF
RULE_ID,
RULE_QUALIFIER_TYPE,
ELEMENT,
OPERATOR,
VALUE,
VALUE_TYPE,
ELEMENT_TYPE,
ELEMENT_VALUE,
REFERENCE_LIST_ID,
AUTHORITY_ID,
START_DATE,
END_DATE
ON sbxtax3.TB_RULE_QUALIFIERS 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW 
     WHEN (
(
decode(NEW.RULE_ID,OLD.RULE_ID,0,1) +
decode(NEW.RULE_QUALIFIER_TYPE,OLD.RULE_QUALIFIER_TYPE,0,1) +
decode(NEW.ELEMENT,OLD.ELEMENT,0,1) +
decode(NEW.OPERATOR,OLD.OPERATOR,0,1) +
decode(NEW.VALUE,OLD.VALUE,0,1) +
decode(NEW.VALUE_TYPE,OLD.VALUE_TYPE,0,1) +
decode(NEW.ELEMENT_TYPE,OLD.ELEMENT_TYPE,0,1) +
decode(NEW.ELEMENT_VALUE,OLD.ELEMENT_VALUE,0,1) +
decode(NEW.REFERENCE_LIST_ID,OLD.REFERENCE_LIST_ID,0,1) +
decode(NEW.AUTHORITY_ID,OLD.AUTHORITY_ID,0,1) +
decode(NEW.START_DATE,OLD.START_DATE,0,1) +
decode(NEW.END_DATE,OLD.END_DATE,0,1)
) > 0
) BEGIN
  INSERT INTO A_RULE_QUALIFIERS (
RULE_QUALIFIER_ID,
RULE_ID,
RULE_QUALIFIER_TYPE,
ELEMENT,
OPERATOR,
VALUE,
VALUE_TYPE,
ELEMENT_TYPE,
ELEMENT_VALUE,
REFERENCE_LIST_ID,
AUTHORITY_ID,
START_DATE,
END_DATE,
CREATED_BY,
CREATION_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
--SYNCHRONIZATION_TIMESTAMP,
RULE_QUALIFIER_ID_O,
RULE_ID_O,
RULE_QUALIFIER_TYPE_O,
ELEMENT_O,
OPERATOR_O,
VALUE_O,
VALUE_TYPE_O,
ELEMENT_TYPE_O,
ELEMENT_VALUE_O,
REFERENCE_LIST_ID_O,
AUTHORITY_ID_O,
START_DATE_O,
END_DATE_O,
CREATED_BY_O,
CREATION_DATE_O,
LAST_UPDATED_BY_O,
LAST_UPDATE_DATE_O,
--SYNCHRONIZATION_TIMESTAMP_O,
CHANGE_TYPE,
--CHANGE_VERSION,
CHANGE_DATE
  ) VALUES (
:NEW.RULE_QUALIFIER_ID,
:NEW.RULE_ID,
:NEW.RULE_QUALIFIER_TYPE,
:NEW.ELEMENT,
:NEW.OPERATOR,
:NEW.VALUE,
:NEW.VALUE_TYPE,
:NEW.ELEMENT_TYPE,
:NEW.ELEMENT_VALUE,
:NEW.REFERENCE_LIST_ID,
:NEW.AUTHORITY_ID,
:NEW.START_DATE,
:NEW.END_DATE,
:NEW.CREATED_BY,
:NEW.CREATION_DATE,
:NEW.LAST_UPDATED_BY,
:NEW.LAST_UPDATE_DATE,
--:NEW.SYNCHRONIZATION_TIMESTAMP,
:OLD.RULE_QUALIFIER_ID,
:OLD.RULE_ID,
:OLD.RULE_QUALIFIER_TYPE,
:OLD.ELEMENT,
:OLD.OPERATOR,
:OLD.VALUE,
:OLD.VALUE_TYPE,
:OLD.ELEMENT_TYPE,
:OLD.ELEMENT_VALUE,
:OLD.REFERENCE_LIST_ID,
:OLD.AUTHORITY_ID,
:OLD.START_DATE,
:OLD.END_DATE,
:OLD.CREATED_BY,
:OLD.CREATION_DATE,
:OLD.LAST_UPDATED_BY,
:OLD.LAST_UPDATE_DATE,
--:OLD.SYNCHRONIZATION_TIMESTAMP,
    'UPDATED',
    --(SELECT CONTENT_VERSION FROM TB_MERCHANTS M, TB_RULES RU WHERE M.MERCHANT_ID = RU.MERCHANT_ID AND RU.RULE_ID = :NEW.RULE_ID),
    SYSDATE);
END;
/